Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2019-12, with the labels that each got.

#82 chore: fix repo org name change
  .travis.yml
  CHANGELOG-v0.1.0-alpha.md
  Makefile
  README.md
  charts/README.md
  docs/csi-dev.md
  docs/read-from-keyvault.md
  pkg/blobfuse/blobfuse.go
  pkg/blobfuse/controllerserver.go
  pkg/blobfuseplugin/main.go
  test/e2e/driver/blobfuse_csi_driver.go
  test/e2e/dynamic_provisioning.go
  test/e2e/pre_provisioning.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/L

#84 chore: update owners
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#81 Enable spell checking and fix spelling issues
  docs/driver-parameters.md
  docs/read-from-keyvault.md
  hack/verify-all.sh
  hack/verify-spelling.sh
  pkg/blobfuse/blobfuse.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#85 Setup code verification and unit test CI
  .gitignore
  .travis.yml
  Makefile
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/latest/blobfuse-csi-driver/values.yaml
  deploy/csi-blobfuse-node.yaml
  hack/verify-all.sh
  hack/verify-dep.sh
  hack/verify-golint.sh
  hack/verify-helm-chart.sh
  hack/verify-spelling.sh
  test/e2e/driver/blobfuse_csi_driver.go
  test/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, size/L
