Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2020-01, with the labels that each got.

#90 s|github.com/kubernetes-sigs|sigs.k8s.io
  Makefile
  charts/README.md
  docs/csi-dev.md
  pkg/blobfuse/blobfuse.go
  pkg/blobfuse/controllerserver.go
  pkg/blobfuseplugin/main.go
  test/e2e/driver/blobfuse_csi_driver.go
  test/e2e/dynamic_provisioning.go
  test/e2e/pre_provisioning.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/integration/integration_test.go
  test/sanity/sanity_test.go
  test/utils/credentials/credentials.go
Labels: cncf-cla: yes, lgtm, size/L

#93 Set up CI for e2e test
  Gopkg.lock
  Makefile
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/run-test.sh
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/manifest/linux.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#92 feat: use standalone blobfuse driver
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-node.yaml
  pkg/blobfuse/nodeserver.go
  pkg/blobfuseplugin/Dockerfile
  pkg/blobfuseplugin/main.go
  test/integration/run-tests-all-clouds.sh
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/feature, size/M

#87 Enable leader election in csi components
  .gitignore
  charts/README.md
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/values.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/rbac-csi-blobfuse-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#94 feat: use NodeStageVolume
  pkg/blobfuse/blobfuse.go
  pkg/blobfuse/nodeserver.go
  pkg/blobfuse/nodeserver_test.go
  test/e2e/suite_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
  test/utils/blobfuse_log.sh
Labels: approved, cncf-cla: yes, kind/feature, size/L

#95 chore: swtich to use mcr repo
  charts/latest/blobfuse-csi-driver/values.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
  pkg/blobfuse/nodeserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#97 set cpu/memory resource limits for blobfuse csi driver
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#100 Set bigger limit
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
  pkg/blobfuse/nodeserver.go
  pkg/blobfuse/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#101 chore: set smaller replica
  charts/latest/blobfuse-csi-driver/values.yaml
  deploy/csi-blobfuse-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#104 doc: fix doc typo
  docs/install-csi-driver-master.md
  docs/install-csi-driver-v0.1.0.md
  docs/install-csi-driver-v0.2.0.md
  docs/install-csi-driver-v0.3.0.md
  docs/install-csi-driver-v0.4.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#105 fix: add missing lease rbac on controller
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml
  charts/v0.4.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.4.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.4.0/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml
  deploy/rbac-csi-blobfuse-controller.yaml
  deploy/v0.4.0/rbac-csi-blobfuse-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#106 chore: fix broken coverage
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#107 chore: add driver pods check
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/L

#108 doc: use nodeStageSecretRef instead of nodePublishSecretRef
  deploy/example/pv-blobfuse-csi.yaml
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS
