Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#125 chore: remove cluster driver registrar
  charts/latest/blobfuse-csi-driver/templates/crd-csi-driver-registry.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-driver.yaml
  charts/latest/blobfuse-csi-driver/values.yaml
  deploy/crd-csi-driver-registry.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-driver.yaml
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#126 fix: set cpu,memory limit to a higher value
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#131 feat: read cloud config from secret
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-secret.yaml
  charts/latest/blobfuse-csi-driver/templates/serviceaccount-csi-blobfuse-node.yaml
  deploy/csi-blobfuse-node.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-blobfuse-controller.yaml
  deploy/rbac-csi-blobfuse-node.yaml
  deploy/uninstall-driver.sh
  docs/read-from-secret.md
  pkg/blobfuse/azure.go
  pkg/blobfuse/azure_test.go
  pkg/blobfuse/blobfuse.go
  pkg/blobfuseplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/documentation, kind/feature, kind/flake, lgtm, size/L

#132 chore: add secret rbac file
  deploy/install-driver.sh
  deploy/rbac-csi-blobfuse-secret.yaml
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/M

#134 fix golint issue
  hack/verify-golint.sh
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/S

#136 feat: add sovereign cloud support
  pkg/blobfuse/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#139 doc: update read from secret doc
  README.md
  docs/read-from-secret.md
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#140 chore: separate secret RBAC
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-node.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-secret.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-blobfuse-controller.yaml
  deploy/rbac-csi-blobfuse-node.yaml
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/L

#141 feat: disable IMDS in controller to support MSI
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
  hack/verify-yamllint.sh
  pkg/blobfuse/blobfuse.go
Labels: approved, cncf-cla: yes, size/S
