Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2020-08, with the labels that each got.

#187 test: remove syscall due to build failure on Windows
  deploy/example/statefulset.yaml
  pkg/blobfuse/nodeserver_test.go
Labels: approved, cncf-cla: yes, size/S

#188 test: add unit-test in blobfuse/controllerserver and csi-common/con-default
  go.mod
  pkg/blobfuse/controllerserver_test.go
  pkg/csi-common/controllerserver-default_test.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/mockstorageaccountclient/doc.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/mockstorageaccountclient/interface.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/XL

#189 feat: support blob storage based NFS
  deploy/example/storageclass-blob-nfs.yaml
  pkg/blobfuse/blobfuse.go
  pkg/blobfuse/blobfuse_test.go
  pkg/blobfuse/controllerserver.go
  pkg/blobfuse/controllerserver_test.go
  pkg/blobfuse/nodeserver.go
  pkg/blobfuseplugin/Dockerfile
  pkg/blobfuseplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, size/L

#191 doc: add NFSv3 support doc
  README.md
  deploy/example/nfs/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#193 doc: rename examples
  deploy/example/deployment.yaml
  deploy/example/e2e_usage.md
  deploy/example/nfs/README.md
  deploy/example/nginx-pod-blob.yaml
  deploy/example/pvc-blob-csi-static.yaml
  deploy/example/pvc-blob-csi.yaml
  deploy/example/statefulset.yaml
  docs/read-from-keyvault.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#194 chore: rename driver name "blob.csi.azure.com"
  README.md
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-driver.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-driver.yaml
  deploy/csi-blobfuse-node.yaml
  deploy/example/e2e_usage.md
  deploy/example/nfs/README.md
  deploy/example/pv-blobfuse-csi-keyvault.yaml
  deploy/example/pv-blobfuse-csi.yaml
  deploy/example/storageclass-blob-nfs.yaml
  deploy/example/storageclass-blobfuse-csi-existing-container.yaml
  deploy/example/storageclass-blobfuse-csi-mountoptions.yaml
  deploy/example/storageclass-blobfuse-csi.yaml
  docs/csi-dev.md
  pkg/blobfuse/blobfuse.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#196 doc: rename driver as "Azure Blob Storage CSI driver"
  README.md
  RELEASE.md
  charts/README.md
  charts/latest/blobfuse-csi-driver/templates/NOTES.txt
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/csi-dev.md
  docs/design.md
  docs/install-blobfuse-csi-driver.md
  docs/install-csi-driver-master.md
  docs/read-from-keyvault.md
  pkg/blobfuseplugin/Dockerfile
  pkg/blobfuseplugin/dev.Dockerfile
  pkg/blobfuseplugin/main.go
  test/e2e/suite_test.go
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#197 chore: rename code path
  Makefile
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
  docs/csi-debug.md
  docs/csi-dev.md
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blobfuse.go
  pkg/blob/blobfuse_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/identityserver.go
  pkg/blob/identityserver_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blob/version.go
  pkg/blob/version_test.go
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/dev.Dockerfile
  pkg/blobplugin/main.go
  test/e2e/driver/blobfuse_csi_driver.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/e2e/testsuites/testsuites.go
  test/integration/run-test.sh
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/feature, size/M

#198 chore: rename driver
  Makefile
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blobfuse.go
  pkg/blob/blobfuse_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/identityserver.go
  pkg/blob/identityserver_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blob/version.go
  pkg/blob/version_test.go
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/main.go
  test/e2e/driver/blobfuse_csi_driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#199 chore: rename controller
  charts/README.md
  charts/latest/blobfuse-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
  deploy/example/metrics/README.md
  deploy/example/metrics/csi-blob-controller-svc.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-blob-controller.yaml
  deploy/uninstall-driver.sh
  docs/csi-debug.md
  docs/install-csi-driver-master.md
  hack/verify-helm-chart.sh
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/feature, size/L

#200 fix: use new naming rule for nfs container
  docs/driver-parameters.md
  pkg/blob/blobfuse.go
  pkg/blob/blobfuse_test.go
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#201 chore: rename node
  charts/latest/blobfuse-csi-driver/templates/csi-blob-driver.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blobfuse-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/latest/blobfuse-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  deploy/csi-blob-driver.yaml
  deploy/csi-blob-node.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-blob-node.yaml
  deploy/uninstall-driver.sh
  docs/csi-debug.md
  docs/install-csi-driver-master.md
  hack/verify-helm-chart.sh
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#202 docs: add blobfuse-v0.6.0 information in index.yaml
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#203 chore: rename driver image
  Makefile
  charts/latest/blobfuse-csi-driver/Chart.yaml
  charts/latest/blobfuse-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  hack/release-image.sh
Labels: approved, cncf-cla: yes, kind/feature, size/M

#204 chore: rename charts
  Makefile
  charts/README.md
  charts/latest/blob-csi-driver/Chart.yaml
  charts/latest/blob-csi-driver/templates/NOTES.txt
  charts/latest/blob-csi-driver/templates/_helpers.tpl
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/example/e2e_usage.md
  deploy/rbac-csi-blob-controller.yaml
  docs/csi-dev.md
  hack/verify-helm-chart.sh
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#205 chore: rename blobfuse test
  README.md
  docs/install-blob-csi-driver.md
  docs/read-from-keyvault.md
  test/e2e/driver/blob_csi_driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#206 chore: rename driver tests
  README.md
  deploy/example/deployment.yaml
  deploy/example/e2e_usage.md
  deploy/example/nginx-pod-blob.yaml
  deploy/example/pv-blobfuse-csi-keyvault.yaml
  deploy/example/pv-blobfuse-csi.yaml
  deploy/example/pvc-blob-csi-static.yaml
  deploy/example/pvc-blob-csi.yaml
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/testsuites.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#207 fix: set correct account prefix for NFS protocol
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#208 doc: renaming in doc
  deploy/example/deployment.yaml
  deploy/example/e2e_usage.md
  docs/design.md
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#209 repository rename
  .travis.yml
  Makefile
  README.md
  RELEASE.md
  charts/README.md
  deploy/example/e2e_usage.md
  deploy/example/metrics/README.md
  deploy/example/nfs/README.md
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/csi-dev.md
  docs/install-csi-driver-master.md
  docs/read-from-keyvault.md
  go.mod
  hack/boilerplate/boilerplate.py
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/main.go
  test/e2e/driver/blob_csi_driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
  test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/integration/integration_test.go
  test/sanity/sanity_test.go
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/cleanup, size/L

#210 test: add unit-test in pkg/blob and server
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver_test.go
  pkg/blobplugin/main.go
  pkg/csi-common/server.go
  pkg/csi-common/server_test.go
  pkg/csi-common/utils.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#211 chore: reduce limit of CPU and Memory
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/M

#212 test: add unit-test in nodeserver and csi-common.
  pkg/blob/fake_mount.go
  pkg/blob/fake_mount_test.go
  pkg/blob/nodeserver_test.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/identityserver-default_test.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#215 test: add unit-test in pkg/blob and pkg/csi-common.
  pkg/blob/azure_test.go
  pkg/blob/controllerserver_test.go
  pkg/blob/fake_mount.go
  pkg/blob/fake_mount_test.go
  pkg/blob/nodeserver_test.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#216 doc: blobfuse example renaming
  deploy/example/e2e_usage.md
  deploy/example/storageclass-blobfuse-existing-container.yaml
  deploy/example/storageclass-blobfuse-mountoptions.yaml
  deploy/example/storageclass-blobfuse-readonly.yaml
  deploy/example/storageclass-blobfuse.yaml
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#217 doc: port num change due to driver rename
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  deploy/example/metrics/README.md
  deploy/example/metrics/csi-blob-controller-svc.yaml
Labels: approved, cncf-cla: yes, size/M

#221 chore: add linux tag for linux deployment
  deploy/example/deployment.yaml
  deploy/example/nginx-pod-blob.yaml
  deploy/example/statefulset.yaml
Labels: approved, cncf-cla: yes, size/XS

#222 chore: adjust cpu/memory limit for blob node pod
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#225 fix: add imagePullSecretsin Helm chart for secret used to pull Docker images
  charts/README.md
  charts/latest/blob-csi-driver/templates/_helpers.tpl
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#226 test: run e2e test on containerd
  deploy/example/metrics/csi-blob-controller-svc.yaml
  docs/csi-debug.md
  hack/verify-yamllint.sh
  test/manifest/linux.json
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/cleanup, kind/test, size/S

#227 Clarify scope of parameters
  deploy/example/e2e_usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#228 doc: fix example docs
  .github/PULL_REQUEST_TEMPLATE.md
  deploy/example/e2e_usage.md
  deploy/example/storageclass-blobfuse-existing-container.yaml
  deploy/example/storageclass-blobfuse-msi.yaml
  deploy/example/storageclass-blobfuse-readonly.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#229 fix: use timestamp for tmp-path
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#230 doc: cut v0.8.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.8.0/blob-csi-driver-v0.8.0.tgz
  charts/v0.8.0/blob-csi-driver/Chart.yaml
  charts/v0.8.0/blob-csi-driver/templates/NOTES.txt
  charts/v0.8.0/blob-csi-driver/templates/_helpers.tpl
  charts/v0.8.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v0.8.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v0.8.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v0.8.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v0.8.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v0.8.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v0.8.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v0.8.0/blob-csi-driver/values.yaml
  deploy/v0.8.0/csi-blob-controller.yaml
  deploy/v0.8.0/csi-blob-driver.yaml
  deploy/v0.8.0/csi-blob-node.yaml
  deploy/v0.8.0/rbac-csi-blob-controller.yaml
  deploy/v0.8.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v0.8.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#231 fix: metrics port and doc issue
  Makefile
  charts/README.md
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/example/metrics/README.md
  deploy/example/metrics/csi-blob-controller-svc.yaml
  pkg/blobplugin/main.go
  test/e2e/suite_test.go
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/bug, size/M
