Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#158 update blobfuseplugin base image with debian-base.
  pkg/blobfuseplugin/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#174 test: add unit-test
  .travis.yml
  pkg/blobfuse/blobfuse_test.go
  pkg/blobfuse/controllerserver_test.go
  pkg/blobfuse/identityserver_test.go
  pkg/blobfuse/nodeserver.go
  pkg/blobfuse/nodeserver_test.go
  pkg/blobfuse/version_test.go
  pkg/csi-common/controllerserver-default_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/XL

#175 chore: update Makefile
  Makefile
Labels: approved, cncf-cla: yes, size/M

#176 fix: installation issue
  deploy/install-driver.sh
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#177 chore: add hack/release-image.sh
  hack/release-image.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#178 test: add dev.Dockerfile
  .travis.yml
  Makefile
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  pkg/blobfuseplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, kind/test, size/M

#182 test: add hack/verify-gomod.sh
  hack/verify-all.sh
  hack/verify-gomod.sh
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/M

#171 test: add negative mount options e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
  test/e2e/testsuites/testsuites.go
  vendor/k8s.io/kubernetes/test/e2e/framework/events/BUILD
  vendor/k8s.io/kubernetes/test/e2e/framework/events/events.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/test, size/L

#183 ci: remove az command
  Makefile
Labels: cncf-cla: yes, size/XS

#184 chore: set default imagePullPolicy
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
  hack/release-image.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#185 doc: cut v0.6.0 release
  README.md
  charts/v0.6.0/blobfuse-csi-driver-v0.6.0.tgz
  charts/v0.6.0/blobfuse-csi-driver/Chart.yaml
  charts/v0.6.0/blobfuse-csi-driver/templates/NOTES.txt
  charts/v0.6.0/blobfuse-csi-driver/templates/_helpers.tpl
  charts/v0.6.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.6.0/blobfuse-csi-driver/templates/csi-blobfuse-driver.yaml
  charts/v0.6.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.6.0/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml
  charts/v0.6.0/blobfuse-csi-driver/templates/rbac-csi-blobfuse-node.yaml
  charts/v0.6.0/blobfuse-csi-driver/templates/serviceaccount-csi-blobfuse-controller.yaml
  charts/v0.6.0/blobfuse-csi-driver/templates/serviceaccount-csi-blobfuse-node.yaml
  charts/v0.6.0/blobfuse-csi-driver/values.yaml
  deploy/v0.6.0/csi-blobfuse-controller.yaml
  deploy/v0.6.0/csi-blobfuse-driver.yaml
  deploy/v0.6.0/csi-blobfuse-node.yaml
  deploy/v0.6.0/rbac-csi-blobfuse-controller.yaml
  deploy/v0.6.0/rbac-csi-blobfuse-node.yaml
  docs/install-blobfuse-csi-driver.md
  docs/install-csi-driver-v0.6.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL
