Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#254 test: enable windows unit tests
  .github/workflows/windows.yaml
  pkg/blob/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/M

#255 Revert "fix: create nonroot user in Dockerfile"
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, size/S

#256 fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#257 CI: enable unit tests for MacOS
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yaml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#258 fix: NFSv3 permission issue with non-root user
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#259 doc: cut v0.10.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.10.0/blob-csi-driver-v0.10.0.tgz
  charts/v0.10.0/blob-csi-driver/Chart.yaml
  charts/v0.10.0/blob-csi-driver/templates/NOTES.txt
  charts/v0.10.0/blob-csi-driver/templates/_helpers.tpl
  charts/v0.10.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v0.10.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v0.10.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v0.10.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v0.10.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v0.10.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v0.10.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v0.10.0/blob-csi-driver/values.yaml
  deploy/v0.10.0/csi-blob-controller.yaml
  deploy/v0.10.0/csi-blob-driver.yaml
  deploy/v0.10.0/csi-blob-node.yaml
  deploy/v0.10.0/rbac-csi-blob-controller.yaml
  deploy/v0.10.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v0.10.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#260 fix: not schedule driver pod on virtual node
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#263 fix: add AzureStorageAuthType to support msi and spn auth
  deploy/example/pv-blobfuse-auth.yaml
  deploy/example/storageclass-blobfuse-msi.yaml
  pkg/blob/blob.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#264 fix: volumeid error in nfs pv
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M
