Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2020-03, with the labels that each got.

#118 feat: add taints to run controller on master node
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/example/deployment.yaml
  deploy/example/statefulset.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#119 fix: correct the behavior of deleting the target direcotory
  pkg/blobfuse/nodeserver.go
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/bug, kind/flake, lgtm, size/S

#120 test: add the e2e test "should use provided credentials"
  pkg/blobfuse/blobfuse.go
  pkg/blobfuse/nodeserver.go
  test/e2e/driver/blobfuse_csi_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#121 chore: replace beta label to GA label for kubernetes.io/os
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.4.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.4.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
  deploy/v0.1.0/csi-blobfuse-controller.yaml
  deploy/v0.1.0/csi-blobfuse-node.yaml
  deploy/v0.2.0/csi-blobfuse-controller.yaml
  deploy/v0.2.0/csi-blobfuse-node.yaml
  deploy/v0.3.0/csi-blobfuse-controller.yaml
  deploy/v0.3.0/csi-blobfuse-node.yaml
  deploy/v0.4.0/csi-blobfuse-controller.yaml
  deploy/v0.4.0/csi-blobfuse-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#122 fix: change imagePullPolicy to IfNotPresent
  Makefile
  charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/latest/blobfuse-csi-driver/values.yaml
  charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.1.0/blobfuse-csi-driver/values.yaml
  charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.2.0/blobfuse-csi-driver/values.yaml
  charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
  charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
  charts/v0.3.0/blobfuse-csi-driver/values.yaml
  charts/v0.4.0/blobfuse-csi-driver/values.yaml
  deploy/csi-blobfuse-controller.yaml
  deploy/csi-blobfuse-node.yaml
  deploy/v0.1.0/csi-blobfuse-controller.yaml
  deploy/v0.1.0/csi-blobfuse-node.yaml
  deploy/v0.2.0/csi-blobfuse-controller.yaml
  deploy/v0.2.0/csi-blobfuse-node.yaml
  deploy/v0.3.0/csi-blobfuse-controller.yaml
  deploy/v0.3.0/csi-blobfuse-node.yaml
  deploy/v0.4.0/csi-blobfuse-controller.yaml
  deploy/v0.4.0/csi-blobfuse-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#123 doc: refine installation scripts
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/install-csi-driver-master.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#124 test: add install/uninstall deployment script test
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M
