Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2020-09, with the labels that each got.

#232 ci: allow override of IMAGE_TAG and E2E_HELM_OPTIONS in Makefile
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#233 fix: Update debian base image to v2.1.3
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#234 feat: bring your own account key for dynamic provisioning
  deploy/example/storageclass-blob-secret.yaml
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#238 fix: set timeout(30s) for csi-provisioner
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
  deploy/example/deployment.yaml
  deploy/example/statefulset.yaml
  test/e2e/driver/blob_csi_driver.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#236 test: add github action
  .github/workflows/ubuntu.yml
  .travis.yml
  Makefile
  pkg/blob/fake_mount.go
  pkg/blob/nodeserver_test.go
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
  vendor/k8s.io/utils/exec/testing/fake_exec.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#240 fix: increase CPU limit for throttling issue
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#241 chore: remove csi-attacher since it's useless
  charts/README.md
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/rbac-csi-blob-controller.yaml
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/bug, size/M

#242 fix: add lock for prevent account list throttling
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#244 test: switch to use mcr nginx image
  Makefile
  deploy/example/deployment.yaml
  deploy/example/nginx-pod-blob.yaml
  deploy/example/statefulset.yaml
  hack/verify-golint.sh
  test/e2e/suite_test.go
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#245 chore: upgrade blobfuse version to 1.3.3
  README.md
Labels: approved, cncf-cla: yes, kind/feature, size/S

#246 fix: mount failure in bring key scenario
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#247 CI: Add `golangci-linter` to github actions
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/S

#248 test: add bring own key e2e test
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/get_storage_account_secret_name.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#249 chore: upgrade to use blobfuse 1.3.4
  README.md
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#250 doc: cut v0.9.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.9.0/blob-csi-driver-v0.9.0.tgz
  charts/v0.9.0/blob-csi-driver/Chart.yaml
  charts/v0.9.0/blob-csi-driver/templates/NOTES.txt
  charts/v0.9.0/blob-csi-driver/templates/_helpers.tpl
  charts/v0.9.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v0.9.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v0.9.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v0.9.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v0.9.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v0.9.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v0.9.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v0.9.0/blob-csi-driver/values.yaml
  deploy/v0.9.0/csi-blob-controller.yaml
  deploy/v0.9.0/csi-blob-driver.yaml
  deploy/v0.9.0/csi-blob-node.yaml
  deploy/v0.9.0/rbac-csi-blob-controller.yaml
  deploy/v0.9.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v0.9.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#251 doc: add bring your own account doc
  README.md
  deploy/example/e2e_usage.md
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#252 fix: create nonroot user in Dockerfile
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, size/S
