Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-04, with the labels that each got.

#374 fix: disable invalid storage class parameters
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#375 fix: add more allowed storage class parameters
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#376 add a new node role for control plane
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#372 feat: Helm Chart pod labels/annotations; configurable limits per component
  charts/README.md
  charts/latest/blob-csi-driver-v1.1.1.tgz
  charts/latest/blob-csi-driver/Chart.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#377 feat: upgrade node driver registrar to v2.1.0
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver-v1.1.1.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#383 fix: wrong version
  charts/README.md
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver-v1.1.1.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#384 Update csi-debug.md
  docs/csi-debug.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#386 add tmp-path parameter in chart config
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#385 fix integration tests by manually un mounting the target path
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/XS

#367 install blobfuse proxy on the host using dameonset
  deploy/blobfuse-proxy/blobfuse-proxy.yaml
  deploy/blobfuse-proxy/v0.1.0/blobfuse-proxy-v0.1.0.deb
  deploy/blobfuse-proxy/v0.1/blobfuse-proxy-v0.1.deb
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/debpackage/etc/systemd/system/blobfuse-proxy.service
  pkg/blobfuse-proxy/main.go
  pkg/blobfuse-proxy/server/server.go
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#389 chore: switch to use k8s.io/mount-utils
  deploy/blobfuse-proxy/blobfuse-proxy.yaml
  go.mod
  pkg/blob/blob.go
  pkg/blob/fake_mount.go
  pkg/blob/fake_mount_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  vendor/k8s.io/utils/mount/OWNERS
  vendor/k8s.io/utils/mount/doc.go
  vendor/k8s.io/utils/mount/fake_mounter.go
  vendor/k8s.io/utils/mount/mount.go
  vendor/k8s.io/utils/mount/mount_helper_common.go
  vendor/k8s.io/utils/mount/mount_helper_unix.go
  vendor/k8s.io/utils/mount/mount_helper_windows.go
  vendor/k8s.io/utils/mount/mount_linux.go
  vendor/k8s.io/utils/mount/mount_unsupported.go
  vendor/k8s.io/utils/mount/mount_windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, size/XXL

#393 test: use mock mount to fix sanity test failures
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
  pkg/blobplugin/main.go
  test/e2e/suite_test.go
  test/integration/run-test.sh
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/failing-test, size/M

#394 fix issues with hack/install-protoc.sh
  hack/install-protoc.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#390 doc: update blobfuse-proxy and bring your own account doc
  Makefile
  README.md
  deploy/example/e2e_usage.md
  hack/install-protoc.sh
  pkg/blobfuse-proxy/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#396 update docker image version
  pkg/blobfuse-proxy/Dockerfile
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#397 chore: refactor Makefile
  Makefile
  pkg/blob/nodeserver.go
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, size/M

#399 fix: controller could run well without cloud provider
  deploy/example/azure.json
  pkg/blob/azure.go
  pkg/blob/azure_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#400 tail blobfuse-proxy logs at the start of blobfuse-proxy daemonset
  Makefile
  deploy/blobfuse-proxy/blobfuse-proxy.yaml
  deploy/blobfuse-proxy/v0.1.0/blobfuse-proxy-v0.1.0.deb
  pkg/blobfuse-proxy/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#395 Add external k8s e2e tests
  Makefile
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, ok-to-test, size/M

#403 feat: support blobfuse v1.3.7
  README.md
  deploy/blobfuse-proxy/blobfuse-proxy.yaml
  deploy/example/storageclass-blobfuse-existing-container.yaml
  deploy/example/storageclass-blobfuse-readonly.yaml
  deploy/example/storageclass-blobfuse.yaml
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/dev.Dockerfile
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#404 cleanup un-used to make targets
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S
