Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#407 fix: remove namespace in ClusterRole
  .github/workflows/windows.yaml
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  deploy/rbac-csi-blob-controller.yaml
  deploy/rbac-csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#408 doc: cut v1.1.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.1.0/blob-csi-driver-v1.1.0.tgz
  charts/v1.1.0/blob-csi-driver/Chart.yaml
  charts/v1.1.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.1.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.1.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.1.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.1.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.1.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.1.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.1.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.1.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.1.0/blob-csi-driver/values.yaml
  deploy/v1.1.0/csi-blob-controller.yaml
  deploy/v1.1.0/csi-blob-driver.yaml
  deploy/v1.1.0/csi-blob-node.yaml
  deploy/v1.1.0/kustomization.yaml
  deploy/v1.1.0/rbac-csi-blob-controller.yaml
  deploy/v1.1.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.1.0.md
Labels: approved, cncf-cla: yes, kind/feature, size/XXL

#409 chore: switch master branch to use v1.2.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#410 create an RPM package for blobfuse-proxy
  pkg/blobfuse-proxy/README.md
  pkg/blobfuse-proxy/rpmbuild/SPECS/utils.spec
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#412 add a new helm parameter for livenessProbe health port
  charts/README.md
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#414 Fix wrongly configured `namespace` for `ClusterRole`
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#415 feat: set blobfuseCachePath in chart installation
  charts/README.md
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#416 chore: use mcr alpine image in blobfuse-proxy
  deploy/blobfuse-proxy/blobfuse-proxy.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#417 fix: second pod mount error for static provisioning(containerName specified)
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/pre_provisioned_multiple_pods.go
Labels: approved, cncf-cla: yes, size/L

#420 chore: upgrade base image to fix CVE issue
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#421 chore: fix image publish script
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#422 chore: upgrade azure lib
  go.mod
  go.sum
  pkg/blob/azure.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/deploymentclient/azure_deploymentclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/azure_diskclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/azure_interfaceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/azure_publicipclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/azure_routeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/azure_routetableclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/azure_snapshotclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/azure_subnetclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmasclient/azure_vmasclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/azure_vmssclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_config.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/reconcile_schema.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/remove.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/XL

#424 fix: incorrect volumeid format
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#426 feat: NFSv3 account dynamic creation support
  go.mod
  go.sum
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#427 test: add nfs e2e test
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/test, size/L

#428 chore: refine update svc endpoint lock
  deploy/example/storageclass-blob-nfs.yaml
  pkg/blob/azure.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#429 Added log for multiple pods command, fexed markup
  docs/csi-debug.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M

#430 fix: RedHat/CentOS issue in helm installation
  README.md
  charts/README.md
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#431 fix: set "host is down" as corrupted mount
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_common.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_helper_windows.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, size/L

#432 fix: remove unnecessary lock in NodePublish
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#433 chore: cleanup yaml config
  charts/README.md
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  deploy/rbac-csi-blob-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/L

#434 feat: support inline volume
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  deploy/csi-blob-driver.yaml
  deploy/example/nginx-blobfuse-inline-volume.yaml
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_inline_volume.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#435 feat: store secret in pod.Namespace if not specified
  charts/latest/blob-csi-driver-v1.2.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#437 test: run more external e2e tests
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: approved, cncf-cla: yes, kind/test, size/S

#436 test: run external test with 1.20 test suites
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#438 test: run external storage test with k8s 1.21 suites
  deploy/example/storageclass-blobfuse.yaml
Labels: approved, cncf-cla: yes, kind/test, size/XS

#439 test: run external tests on NFS
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#441 fix: sercretNamesapce empty issue in old driver PV
  pkg/blob/blob.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#442 doc: cut v1.2.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.2.0/blob-csi-driver-v1.2.0.tgz
  charts/v1.2.0/blob-csi-driver/Chart.yaml
  charts/v1.2.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.2.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.2.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.2.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.2.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.2.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.2.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.2.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.2.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.2.0/blob-csi-driver/values.yaml
  deploy/v1.2.0/csi-blob-controller.yaml
  deploy/v1.2.0/csi-blob-driver.yaml
  deploy/v1.2.0/csi-blob-node.yaml
  deploy/v1.2.0/kustomization.yaml
  deploy/v1.2.0/rbac-csi-blob-controller.yaml
  deploy/v1.2.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#445 fix: only use pod.Namespace in inline volume support
  deploy/example/nginx-blobfuse-inline-volume.yaml
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#446 fix: only read secret for inline volume
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#447 feat: support fsGroupPolicy for NFS
  Makefile
  charts/README.md
  charts/latest/blob-csi-driver-v1.3.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/latest/blob-csi-driver/values.yaml
  test/external-e2e/run.sh
  test/external-e2e/testdriver-blobfuse.yaml
  test/external-e2e/testdriver-nfs.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/M
