Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-07, with the labels that each got.

#467 feat: support alternative driver name
  charts/README.md
  charts/latest/blob-csi-driver-v1.4.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/version.go
  pkg/blob/version_test.go
  pkg/blobplugin/main.go
  test/e2e/driver/blob_csi_driver.go
  test/e2e/suite_test.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#468 fix: remove node metricsPort
  charts/latest/blob-csi-driver-v1.4.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#469 spelling corrections
  docs/csi-debug.md
  docs/csi-dev.md
  docs/design.md
  docs/install-csi-driver-v0.1.0.md
  docs/install-csi-driver-v0.2.0.md
  docs/install-csi-driver-v0.3.0.md
  docs/install-csi-driver-v0.4.0.md
  docs/install-driver-on-aks.md
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, ok-to-test, size/S

#470 fix: conflict inline volume mount options with default
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#471 feat: bring you own service accounts in helm install
  charts/README.md
  charts/latest/blob-csi-driver-v1.4.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  hack/verify-examples.sh
  test/external-e2e/run.sh
  test/external-e2e/testdriver-blobfuse.yaml
  test/external-e2e/testdriver-nfs.yaml
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, kind/feature, size/L

#472 doc: update chart doc
  charts/README.md
  charts/latest/blob-csi-driver-v1.4.0.tgz
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#475 fix: unmount failure due to incorrect mount path check
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#476 chore: refine driver parameter setting
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blobplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#477 feat: add cloudConfigSecret in helm install
  charts/README.md
  charts/latest/blob-csi-driver-v1.4.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blobplugin/main.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#479 fix: blobfuse mount silent failure issue
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#480 fix: huge storage account list usage
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#481 feat: customize controller hostNetwork setting in helm install
  charts/README.md
  charts/latest/blob-csi-driver-v1.4.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#478 doc: cut v1.4.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.4.0/blob-csi-driver-v1.4.0.tgz
  charts/v1.4.0/blob-csi-driver/Chart.yaml
  charts/v1.4.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.4.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.4.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.4.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.4.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.4.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.4.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.4.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.4.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.4.0/blob-csi-driver/values.yaml
  deploy/v1.4.0/csi-blob-controller.yaml
  deploy/v1.4.0/csi-blob-driver.yaml
  deploy/v1.4.0/csi-blob-node.yaml
  deploy/v1.4.0/kustomization.yaml
  deploy/v1.4.0/rbac-csi-blob-controller.yaml
  deploy/v1.4.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.4.0.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, size/XXL

#482 chore: switch master branch to use v1.5.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.4.0.tgz
  charts/latest/blob-csi-driver-v1.5.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M
