Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#336 fix: use Environment.StorageEndpointSuffix if not specified
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#337 fix: always initialize driver cloud config
  pkg/blob/azure.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#338 test: add expand volume integration test
  pkg/blob/azure_test.go
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#341 test: add verify-helm-chart-files.sh
  charts/index.yaml
  hack/verify-all.sh
  hack/verify-helm-chart-files.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/L

#342 test: set lower loglevel in e2e test
  Makefile
  charts/README.md
  charts/latest/blob-csi-driver-v1.0.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
  charts/latest/blob-csi-driver/templates/NOTES.txt
  charts/latest/blob-csi-driver/templates/_helpers.tpl
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#343 chore: adjust log level for some CSI operations
  Makefile
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#344 fix: set default logLevel value for helm charts
  charts/latest/blob-csi-driver-v1.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  hack/verify-helm-chart-files.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#348 fix: Use current value of resource group's managedBy property
  test/utils/azure/azure_helper.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#345 feat: add imagepullsecrets in helm chart
  charts/latest/blob-csi-driver-v1.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#351 fix: imagePullsecrets issue
  charts/latest/blob-csi-driver-v1.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  hack/verify-helm-chart-files.sh
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#352 chore: change authEnv setting
  Makefile
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#353 doc: cut v1.0.0 GA release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.0.0/blob-csi-driver-v1.0.0.tgz
  charts/v1.0.0/blob-csi-driver/Chart.yaml
  charts/v1.0.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.0.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.0.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.0.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.0.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.0.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.0.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.0.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.0.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.0.0/blob-csi-driver/values.yaml
  deploy/v1.0.0/csi-blob-controller.yaml
  deploy/v1.0.0/csi-blob-driver.yaml
  deploy/v1.0.0/csi-blob-node.yaml
  deploy/v1.0.0/rbac-csi-blob-controller.yaml
  deploy/v1.0.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.0.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#354 chore: switch master branch to use v1.1.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.0.0.tgz
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#355 fix: increate csi-resizer memory limit
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
