Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-12, with the labels that each got.

#576 feat: blobfuse v1.4.2 support
  README.md
  charts/README.md
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes, do-not-merge/hold

#578 fix: avoid using different mount path in remount on v1.4
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#577 fix: update v1.7.0 chart
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/v1.7.0/blob-csi-driver-v1.7.0.tgz
  charts/v1.7.0/blob-csi-driver/Chart.yaml
  hack/verify-helm-chart.sh
Labels: kind/bug, approved, cncf-cla: yes, size/M

#580 doc: add v1.4.1 artifacts in master branch
  charts/index.yaml
  charts/v1.4.1/blob-csi-driver-v1.4.1.tgz
  charts/v1.4.1/blob-csi-driver/Chart.yaml
  charts/v1.4.1/blob-csi-driver/templates/NOTES.txt
  charts/v1.4.1/blob-csi-driver/templates/_helpers.tpl
  charts/v1.4.1/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.4.1/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.4.1/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.4.1/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.4.1/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.4.1/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.4.1/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.4.1/blob-csi-driver/values.yaml
  deploy/v1.4.1/csi-blob-controller.yaml
  deploy/v1.4.1/csi-blob-driver.yaml
  deploy/v1.4.1/csi-blob-node.yaml
  deploy/v1.4.1/kustomization.yaml
  deploy/v1.4.1/rbac-csi-blob-controller.yaml
  deploy/v1.4.1/rbac-csi-blob-node.yaml
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#582 chore: update csicommon to csi spec v1.5
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/nodeserver-default_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, kind/cleanup, size/L

#583 chore: remove nfs-kernel-server package
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#584 feat: disable updateDB on blobfuse to save account list usage
  charts/README.md
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy.yaml
  deploy/example/disable-updatedb-ds.yaml
Labels: kind/feature, approved, cncf-cla: yes, do-not-merge/hold, size/M

#585 feat: add append-timestamp-cache-dir support in chart
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  pkg/blobplugin/main.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#586 chore: enable build test in windows GitHub action
  .github/workflows/windows.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test, kind/cleanup

#587 chore: enable blob csi driver to reuse csicommon implementation for unimplemented APIs
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/nodeserver-default_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, kind/cleanup, size/L

#588 test: add apiVersion verification test
  .github/workflows/pluto.yaml
Labels: kind/test, size/S, approved, cncf-cla: yes

#589 fix: CVE-2021-43618 in Ubuntu image
  .github/workflows/pluto.yaml
  pkg/blobplugin/Dockerfile
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#590 fix: CVE-2021-38561 with golang lib
  go.mod
  go.sum
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/M

#591 feat: add secretName in storage class parameters
  docs/driver-parameters.md
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, approved, cncf-cla: yes, do-not-merge/hold, size/M

#592 fix: return error earlier when subnetName is empty
  pkg/blob/azure.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#593 cleanup: remove cpu limits
  charts/README.md
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#594 feat: add mountPermissions config in driver
  charts/README.md
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  pkg/blobplugin/main.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#595 feat: support arm64
  Makefile
  pkg/blobplugin/Dockerfile
  test/integration/run-test.sh
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#596 chore: refactor Dockerfile
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup
