Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-01, with the labels that each got.

#305 doc: add v0.7.1 deployment
  README.md
  charts/v0.7.1/blob-csi-driver/Chart.yaml
  charts/v0.7.1/blob-csi-driver/templates/NOTES.txt
  charts/v0.7.1/blob-csi-driver/templates/_helpers.tpl
  charts/v0.7.1/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v0.7.1/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v0.7.1/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v0.7.1/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v0.7.1/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v0.7.1/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v0.7.1/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v0.7.1/blob-csi-driver/values.yaml
  deploy/v0.7.1/csi-blob-controller.yaml
  deploy/v0.7.1/csi-blob-driver.yaml
  deploy/v0.7.1/csi-blob-node.yaml
  deploy/v0.7.1/rbac-csi-blob-controller.yaml
  deploy/v0.7.1/rbac-csi-blob-node.yaml
  docs/install-csi-driver-v0.7.1.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#269 doc: cut v0.11.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.11.0/blob-csi-driver-v0.11.0.tgz
  charts/v0.11.0/blob-csi-driver/Chart.yaml
  charts/v0.11.0/blob-csi-driver/templates/NOTES.txt
  charts/v0.11.0/blob-csi-driver/templates/_helpers.tpl
  charts/v0.11.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v0.11.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v0.11.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v0.11.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v0.11.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v0.11.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v0.11.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v0.11.0/blob-csi-driver/values.yaml
  deploy/v0.11.0/csi-blob-controller.yaml
  deploy/v0.11.0/csi-blob-driver.yaml
  deploy/v0.11.0/csi-blob-node.yaml
  deploy/v0.11.0/rbac-csi-blob-controller.yaml
  deploy/v0.11.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v0.11.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#306 test: enable GH actions on all branches
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yaml
Labels: approved, cncf-cla: yes, kind/test, size/S

#307 doc: update helm chart doc
  charts/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#311 fix: ssl cert issue on non-debian agent node
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#310 feat: Add kubelet path parameter in helm chart installation
  charts/README.md
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#312 chore: upgrade resizer to v1.1.0
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#314 fix: account creation lock issue
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#313 fix: mount certs for Azure Stack
  Makefile
  README.md
  charts/README.md
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#315 fix: update v0.11.0 chart
  charts/v0.11.0/blob-csi-driver-v0.11.0.tgz
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#316 fix: remove ssl in v0.11.0
  charts/v0.11.0/blob-csi-driver-v0.11.0.tgz
  charts/v0.11.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v0.11.0/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/v0.11.0/csi-blob-controller.yaml
  deploy/v0.11.0/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#318 test: run non-root container test
  Makefile
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset.yaml
  hack/verify-examples.sh
  test/utils/check_driver_pods_restart.sh
  test/utils/get_storage_account_secret_name.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#319 chore: Fix git clone directory path
  docs/csi-dev.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#321 fix: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blob/volume_lock.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/L

#322 test: refactor example verification test
  Makefile
  hack/verify-examples.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#323 fix: passing CLOUD correctly in Makefile for Azure Stack
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#324 fix: reduce driver logs
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  pkg/blob/controllerserver.go
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/server.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#325 fix: Azure Stack supports Premium_LRS storage account type
  docs/limitations.md
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#326 fix: optimize test object creation
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#327 chore: upgrade livenessprobe to v2.2.0
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#328 feat: add lock in controller
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/S

#329 feat: add controller metrics
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#308 feat: remove dependency of azure.json in node server
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  pkg/blobplugin/main.go
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#330 chore: upgrade azure lib
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/blob/azure.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/azure_diskclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/azure_interfaceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/azure_publicipclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/azure_routeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/azure_routetableclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/azure_snapshotclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/azure_subnetclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/azure_vmssclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XXL

#331 cleanup: remove useless logs
  pkg/blob/identityserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#332 Execute `df -h` command in the container for demo becuse bash is no longer installed in
  deploy/example/e2e_usage.md
Labels: cncf-cla: yes, kind/documentation, ok-to-test, size/XS

#333 fix: update helm chart
  .gitignore
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.0.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#334 test: add helm chart tgz file verification
  .github/workflows/darwin.yaml
  .github/workflows/linux.yaml
  .github/workflows/windows.yaml
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#335 test: add chart tgz files verification
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/S
