Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#359 test: fix go mod issue with go1.16
  .github/workflows/darwin.yaml
  .github/workflows/linux.yaml
  go.mod
Labels: approved, cncf-cla: yes, kind/test, size/XS

#349 use blobfuse-proxy agent that runs on nodes to maintain blobfuse mounts
  Makefile
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blobplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#363 feat: upgrade csi-provisioner to v2.1.0
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#364 chore: increase csi-resizer memory limit
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#362 Replace labels to follow Helm Best Practices and prevent pod recreati…
  charts/latest/blob-csi-driver-v1.1.0.tgz
  charts/latest/blob-csi-driver/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#365 feat: add kustomize in deployment
  deploy/kustomization.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#366 create a debian .deb package for blobfuse-proxy
  .gitignore
  pkg/blobfuse-proxy/README.md
  pkg/blobfuse-proxy/debpackage/DEBIAN/control
  pkg/blobfuse-proxy/debpackage/etc/systemd/system/blobfuse-proxy.service
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#368 add blobfuse-proxy v0.1 .deb package
  .gitignore
  Makefile
  deploy/blobfuse-proxy/v0.1/blobfuse-proxy-v0.1.deb
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS
