Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2021-11, with the labels that each got.

#557 fix: increase sidecar container cpu limit
  charts/latest/blob-csi-driver-v1.6.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes, lgtm

#559 chore: increase sidecar container memory limit
  charts/latest/blob-csi-driver-v1.6.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#560 Refactoring Kubernetes labels and add custom labels
  charts/README.md
  charts/latest/blob-csi-driver-v1.6.0.tgz
  charts/latest/blob-csi-driver/templates/_helpers.tpl
  charts/latest/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#561 chore: upgrade sidecar container versions
  charts/README.md
  charts/latest/blob-csi-driver-v1.6.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#562 feat: add allowEmptyCloudConfig config in chart
  charts/README.md
  charts/latest/blob-csi-driver-v1.6.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blobplugin/main.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#564 fix: avoid using different mount path in remount
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#566 chore: upgrade azure lib
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednsclient/azure_privatednsclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#565 feat: disable GET_VOLUME_STATS by default
  README.md
  charts/README.md
  charts/latest/blob-csi-driver-v1.6.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/blob.go
  pkg/blobplugin/main.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#567 fix: master branch chart
  charts/latest/blob-csi-driver-v1.6.0.tgz
  charts/latest/blob-csi-driver-v1.7.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#571 fix: v1.6.0 chart index
  charts/index.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/M

#570 feat: increase sidecar container cpu limits
  charts/README.md
  charts/latest/blob-csi-driver-v1.7.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#568 doc: cut v1.7.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.7.0.tgz
  charts/v1.7.0/blob-csi-driver-v1.7.0.tgz
  charts/v1.7.0/blob-csi-driver/Chart.yaml
  charts/v1.7.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.7.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.7.0/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/v1.7.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.7.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.7.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.7.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.7.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.7.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.7.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.7.0/blob-csi-driver/values.yaml
  deploy/v1.7.0/blobfuse-proxy.yaml
  deploy/v1.7.0/csi-blob-controller.yaml
  deploy/v1.7.0/csi-blob-driver.yaml
  deploy/v1.7.0/csi-blob-node.yaml
  deploy/v1.7.0/kustomization.yaml
  deploy/v1.7.0/rbac-csi-blob-controller.yaml
  deploy/v1.7.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.7.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation, do-not-merge/hold

#572 chore: switch master branch to use v1.8.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.7.0.tgz
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#573 feat: remove mlocate by default in blobfuse-proxy install to save account list usage
  charts/README.md
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy.yaml
  deploy/kustomization.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#574 doc: add remove-mlocate daemonset
  deploy/example/remove-mlocate-ds.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M
