Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#781 fix: increase api qps for blob kubeclient
  pkg/blob/azure.go
  pkg/blob/azure_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#785 feat: make kube-api-qps configurable
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blobplugin/main.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#786 cleanup: remove unused install docs
  docs/install-csi-driver-v0.1.0.md
  docs/install-csi-driver-v0.10.0.md
  docs/install-csi-driver-v0.11.0.md
  docs/install-csi-driver-v0.2.0.md
  docs/install-csi-driver-v0.3.0.md
  docs/install-csi-driver-v0.4.0.md
  docs/install-csi-driver-v0.5.0.md
  docs/install-csi-driver-v0.6.0.md
  docs/install-csi-driver-v0.7.0.md
  docs/install-csi-driver-v0.7.1.md
  docs/install-csi-driver-v0.8.0.md
  docs/install-csi-driver-v0.9.0.md
Labels: approved, cncf-cla: yes, kind/cleanup, size/L

#784 feat: support blobfuse2 on Ubuntu 22.04 node
  go.mod
  go.sum
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/main.go
  pkg/blobfuse-proxy/server/server.go
  pkg/blobplugin/Dockerfile
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_sastoken_tester.go
  vendor/github.com/go-ini/ini/.editorconfig
  vendor/github.com/go-ini/ini/.gitignore
  vendor/github.com/go-ini/ini/.golangci.yml
  vendor/github.com/go-ini/ini/LICENSE
  vendor/github.com/go-ini/ini/Makefile
  vendor/github.com/go-ini/ini/README.md
  vendor/github.com/go-ini/ini/codecov.yml
  vendor/github.com/go-ini/ini/data_source.go
  vendor/github.com/go-ini/ini/deprecated.go
  vendor/github.com/go-ini/ini/error.go
  vendor/github.com/go-ini/ini/file.go
  vendor/github.com/go-ini/ini/helper.go
  vendor/github.com/go-ini/ini/ini.go
  vendor/github.com/go-ini/ini/key.go
  vendor/github.com/go-ini/ini/parser.go
  vendor/github.com/go-ini/ini/section.go
  vendor/github.com/go-ini/ini/struct.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test

#787 fix: make sure blobfuse2 is installed when init blobfuse node driver
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/server/server.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#788 feat: support fuse2 protocol in storageclass
  docs/driver-parameters.md
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blobfuse-proxy/pb/azure_blob_mount.pb.go
  pkg/blobfuse-proxy/proto/azure_blob_mount.proto
  pkg/blobfuse-proxy/server/server.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#789 doc: cut v1.18.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.18.0/blob-csi-driver-v1.18.0.tgz
  charts/v1.18.0/blob-csi-driver/Chart.yaml
  charts/v1.18.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.18.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.18.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.18.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.18.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.18.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.18.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.18.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.18.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.18.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.18.0/csi-blob-controller.yaml
  deploy/v1.18.0/csi-blob-driver.yaml
  deploy/v1.18.0/csi-blob-node.yaml
  deploy/v1.18.0/kustomization.yaml
  deploy/v1.18.0/rbac-csi-blob-controller.yaml
  deploy/v1.18.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.18.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation
