Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#690 feat: upgrade to blobfuse v1.4.4
  README.md
  charts/latest/blob-csi-driver-v1.14.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#694 feat: add runOnControlPlane in chart config
  Makefile
  charts/README.md
  charts/latest/blob-csi-driver-v1.14.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: kind/feature, approved, cncf-cla: yes, size/M

#691 feat: combine blobfuse-proxy daemonset with driver node daemonset
  .github/workflows/linux.yaml
  .gitignore
  Makefile
  charts/latest/blob-csi-driver-v1.14.0.tgz
  charts/latest/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy.yaml
  deploy/csi-blob-node.yaml
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/install-csi-driver-master.md
  pkg/blobfuse-proxy/blobfuse-proxy.service
  pkg/blobfuse-proxy/debpackage/DEBIAN/control
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/rpmbuild/SPECS/utils.spec
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#697 doc: cut v1.14.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.14.0.tgz
  charts/v1.14.0/blob-csi-driver-v1.14.0.tgz
  charts/v1.14.0/blob-csi-driver/Chart.yaml
  charts/v1.14.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.14.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.14.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.14.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.14.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.14.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.14.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.14.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.14.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.14.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.14.0/csi-blob-controller.yaml
  deploy/v1.14.0/csi-blob-driver.yaml
  deploy/v1.14.0/csi-blob-node.yaml
  deploy/v1.14.0/kustomization.yaml
  deploy/v1.14.0/rbac-csi-blob-controller.yaml
  deploy/v1.14.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.14.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#699 chore: switch master branch to use v1.15.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.14.0.tgz
  charts/latest/blob-csi-driver-v1.15.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#704 upgrade sidecar image versions and fixed CVE-2022-28948 in image build
  charts/README.md
  charts/latest/blob-csi-driver-v1.15.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, size/M

#707 fix: open file num limit setting issue and KillMode in blobfuse-proxy
  pkg/blobfuse-proxy/blobfuse-proxy.service
Labels: kind/bug, size/S, approved, cncf-cla: yes

#708 feat: support pv/pvc metadata for containerName parameter
  docs/driver-parameters.md
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#710 chore: shorten userAgent
  pkg/blob/version.go
  pkg/blob/version_test.go
Labels: approved, cncf-cla: yes, size/XS

#711 doc: cut v1.15.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.15.0.tgz
  charts/v1.15.0/blob-csi-driver-v1.15.0.tgz
  charts/v1.15.0/blob-csi-driver/Chart.yaml
  charts/v1.15.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.15.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.15.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.15.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.15.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.15.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.15.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.15.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.15.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.15.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.15.0/csi-blob-controller.yaml
  deploy/v1.15.0/csi-blob-driver.yaml
  deploy/v1.15.0/csi-blob-node.yaml
  deploy/v1.15.0/kustomization.yaml
  deploy/v1.15.0/rbac-csi-blob-controller.yaml
  deploy/v1.15.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.15.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#713 chore: switch master branch to use v1.16.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.15.0.tgz
  charts/latest/blob-csi-driver-v1.16.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M
