Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#747 cleanup: remove v1.16.0/blob-csi-driver-v0.0.0.tgz chart file
  charts/index.yaml
  charts/v1.16.0/blob-csi-driver-v0.0.0.tgz
Labels: approved, cncf-cla: yes, size/M, kind/cleanup

#751 fix: delete volume failure when management api is throttled
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#753 add e2e test for resourceID
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/utils/azure/keyvault_helper.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#757 Resolved issue of broken link
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#758 feat: support https proxy and http proxy in chart config
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes, lgtm, ok-to-test

#761 fix: restart blobfuse proxy when necessary
  pkg/blobfuse-proxy/README.md
  pkg/blobfuse-proxy/init.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#760 feat: add helm repo install check
  hack/verify-all.sh
  hack/verify-helm-chart-index.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test
