Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#765 chore: upgrade base image debian-base:bullseye-v1.4.2
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#759 feat: set read-ahead for nfs mount
  pkg/blobfuse-proxy/init.sh
Labels: size/S, approved, cncf-cla: yes, lgtm, ok-to-test

#771 test: add restart driver e2e test
  test/e2e/driver/blob_csi_driver.go
  test/e2e/driver/driver.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/utils/restart_driver_daemonset.sh
Labels: kind/test, approved, cncf-cla: yes, size/L

#776 fix: rm blobfuse-proxy before cp to avoid Text file busy error
  pkg/blobfuse-proxy/init.sh
Labels: kind/bug, approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#777 doc: cut v1.17.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.17.0/blob-csi-driver-v1.17.0.tgz
  charts/v1.17.0/blob-csi-driver/Chart.yaml
  charts/v1.17.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.17.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.17.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.17.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.17.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.17.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.17.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.17.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.17.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.17.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.17.0/csi-blob-controller.yaml
  deploy/v1.17.0/csi-blob-driver.yaml
  deploy/v1.17.0/csi-blob-node.yaml
  deploy/v1.17.0/kustomization.yaml
  deploy/v1.17.0/rbac-csi-blob-controller.yaml
  deploy/v1.17.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.17.0.md
  hack/verify-helm-chart-index.sh
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#780 feat: increase api qps limit of csi-provisioner
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS
