Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2022-05, with the labels that each got.

#672 feat: skip chmod if mountPermissions is 0 after mount
  docs/driver-parameters.md
  pkg/blob/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, approved, cncf-cla: yes, size/M

#674 test: run k8s 1.24 external e2e test
  test/external-e2e/run.sh
Labels: kind/test, approved, cncf-cla: yes, size/XS

#675 chore: add cloud config logging in driver init
  pkg/blob/blob.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#676 fix: bypass chmod if mounting point permissions are correct
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#677 chore: allow dpkg-deb to be run via docker
  Makefile
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test, kind/cleanup

#678 chore: set as info log if cloud-provider-azure secret not found
  pkg/blob/azure.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#679 doc: cut v1.12.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.12.0.tgz
  charts/v1.12.0/blob-csi-driver-v1.12.0.tgz
  charts/v1.12.0/blob-csi-driver/Chart.yaml
  charts/v1.12.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.12.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.12.0/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/v1.12.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.12.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.12.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.12.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.12.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.12.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.12.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.12.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.12.0/blobfuse-proxy.yaml
  deploy/v1.12.0/csi-blob-controller.yaml
  deploy/v1.12.0/csi-blob-driver.yaml
  deploy/v1.12.0/csi-blob-node.yaml
  deploy/v1.12.0/kustomization.yaml
  deploy/v1.12.0/rbac-csi-blob-controller.yaml
  deploy/v1.12.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.12.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#681 chore: switch master branch to use v1.13.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.12.0.tgz
  charts/latest/blob-csi-driver-v1.13.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#683 fix: respect DisableAzureStackCloud on AKS control plane setting
  pkg/blob/azure.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#685 fix: incorrect runOnMaster label config
  Makefile
  charts/latest/blob-csi-driver-v1.13.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  test/external-e2e/run.sh
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#686 doc: cut v1.13.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.13.0.tgz
  charts/v1.13.0/blob-csi-driver-v1.13.0.tgz
  charts/v1.13.0/blob-csi-driver/Chart.yaml
  charts/v1.13.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.13.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.13.0/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/v1.13.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.13.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.13.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.13.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.13.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.13.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.13.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.13.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.13.0/blobfuse-proxy.yaml
  deploy/v1.13.0/csi-blob-controller.yaml
  deploy/v1.13.0/csi-blob-driver.yaml
  deploy/v1.13.0/csi-blob-node.yaml
  deploy/v1.13.0/kustomization.yaml
  deploy/v1.13.0/rbac-csi-blob-controller.yaml
  deploy/v1.13.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.13.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation
