Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2022-01, with the labels that each got.

#598 fix the Confirmed field of ValidateVolumeCapabilities response
  pkg/blob/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#599 test: add one sanity test
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#602 doc: cut v1.8.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/v1.8.0/blob-csi-driver-v1.8.0.tgz
  charts/v1.8.0/blob-csi-driver/Chart.yaml
  charts/v1.8.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.8.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.8.0/blob-csi-driver/templates/blobfuse-proxy.yaml
  charts/v1.8.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.8.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.8.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.8.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.8.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.8.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.8.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.8.0/blob-csi-driver/values.yaml
  deploy/v1.8.0/blobfuse-proxy.yaml
  deploy/v1.8.0/csi-blob-controller.yaml
  deploy/v1.8.0/csi-blob-driver.yaml
  deploy/v1.8.0/csi-blob-node.yaml
  deploy/v1.8.0/kustomization.yaml
  deploy/v1.8.0/rbac-csi-blob-controller.yaml
  deploy/v1.8.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.8.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#603 chore: switch master branch to use v1.9.0
  Makefile
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.8.0.tgz
  charts/latest/blob-csi-driver-v1.9.0.tgz
  charts/latest/blob-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#605 chore: upgrade to csi-provisioner v3.1.0
  .github/workflows/static.yaml
  README.md
  charts/README.md
  charts/latest/blob-csi-driver-v1.9.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  test/external-e2e/run.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#606 test: add more golinters
  .github/workflows/static.yaml
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blobfuse-proxy/server/server.go
  pkg/blobplugin/main.go
  test/e2e/testsuites/testsuites.go
  test/utils/azure/azure_helper.go
  test/utils/credentials/credentials.go
Labels: kind/test, approved, cncf-cla: yes, size/M

#607 fix: CVE-2021-3996 in image build
  pkg/blobplugin/Dockerfile
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#609 feat: upgrade to csi-resizer v1.4.0
  charts/README.md
  charts/latest/blob-csi-driver-v1.9.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#610 cleanup: remove unused code
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/identityserver-default_test.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/nodeserver-default_test.go
  pkg/csi-common/utils.go
Labels: approved, cncf-cla: yes, size/XL, kind/cleanup
