Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-10, with the labels that each got.

#1028 cleanup: fix typo
  test/e2e/driver/blob_csi_driver.go
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1027 doc: refine inline volume example
  deploy/example/e2e_usage.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1029 test: remove override in blobfuse proxy enabled test
  Makefile
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1031 test: fix verify-helm-chart failure
  .github/workflows/linux.yaml
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1040 test: adjust log print in e2e test
  hack/verify-examples.sh
  test/external-e2e/testdriver-blobfuse.yaml
  test/external-e2e/testdriver-nfs.yaml
  test/utils/blob_log.sh
Labels: kind/test, size/S, approved, cncf-cla: yes

#1051 cleanup: fix k8s.io/endpointslice dependency
  go.mod
  hack/verify-gomod.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1054 test: don't return error in blob_log.sh
  Makefile
  test/utils/blob_log.sh
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1055 fix: support arm in init.sh
  pkg/blobfuse-proxy/init.sh
Labels: kind/bug, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1059 fix: nfs volume creation failure due to Microsoft.Storage.Global Service endpoint enabled
  pkg/blob/azure.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1069 feat: add node metrics
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#914 feat: support volume cloning
  .trivyignore
  deploy/csi-blob-controller.yaml
  deploy/example/pvc-blob-csi-clone.yaml
  hack/boilerplate/boilerplate.generatego.txt
  hack/boilerplate/boilerplate.gomock.txt
  hack/boilerplate/boilerplate.py
  hack/update-mock.sh
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/main.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/utils_test.go
  pkg/util/util.go
  pkg/util/util_mock.go
  pkg/util/util_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
  test/e2e/testsuites/specs.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver-blobfuse.yaml
  test/external-e2e/testdriver-nfs.yaml
  test/sanity/run-test.sh
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test

#1072 doc: correct check blob csi pod status doc
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/NOTES.txt
Labels: approved, cncf-cla: yes, kind/documentation, size/XS, lgtm, ok-to-test

#1074 [release-1.23] fix: increase provisioner timeout as 20min
  charts/latest/blob-csi-driver-v1.23.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1081 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes
