Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-01, with the labels that each got.

#808 test: add helm lint test
  hack/verify-helm-chart.sh
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test

#806 feat: support privateendpoint
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/mockvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#811 doc: cut v1.19.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.19.0/blob-csi-driver-v1.19.0.tgz
  charts/v1.19.0/blob-csi-driver/Chart.yaml
  charts/v1.19.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.19.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.19.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.19.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.19.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.19.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.19.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.19.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.19.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.19.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.19.0/csi-blob-controller.yaml
  deploy/v1.19.0/csi-blob-driver.yaml
  deploy/v1.19.0/csi-blob-node.yaml
  deploy/v1.19.0/kustomization.yaml
  deploy/v1.19.0/rbac-csi-blob-controller.yaml
  deploy/v1.19.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.19.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#813 add e2e test for unmount deleted volume
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_unmount_tester.go
  test/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#816 doc: refine doc
  deploy/example/e2e_usage.md
  deploy/example/pv-blobfuse-auth.yaml
  deploy/example/pv-blobfuse-csi-keyvault.yaml
  deploy/example/pv-blobfuse-csi.yaml
  deploy/example/pv-blobfuse-nfs.yaml
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M
