Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-04, with the labels that each got.

#859 [release-1.20] fix: wait to make sure blobfuse mount complete before bind mount
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blobfuse-proxy/server/server.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/L

#857 feat: support install specific blobfuse version using blobfuse-proxy
  README.md
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  test/utils/blob_log.sh
Labels: kind/bug, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#864 cleanup: remove context.TODO
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#866 feat: enable securityContext.seccompProfile
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#867 fix: support getting sasToken, msiSecret, SPN from secret
  hack/verify-examples.sh
  pkg/blob/blob.go
  pkg/blob/blob_test.go
Labels: kind/bug, kind/feature, approved, cncf-cla: yes, size/L

#870 [release-1.20] fix: support getting sasToken, msiSecret, SPN from secret
  hack/verify-examples.sh
  pkg/blob/blob.go
  pkg/blob/blob_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#871 fix: add securityContext.seccompProfile for driver controller
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#873 test(e2e): change the storageclass configuration method in the test file
  deploy/example/nfs/statefulset.yaml
  deploy/example/statefulset-nfs.yaml
  deploy/example/statefulset-nonroot-nfs.yaml
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, ok-to-test, kind/cleanup

#878 doc: update supported version and cleanup deprecated versions
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.19.3/blob-csi-driver-v1.19.3.tgz
  charts/v1.19.3/blob-csi-driver/Chart.yaml
  charts/v1.19.3/blob-csi-driver/templates/NOTES.txt
  charts/v1.19.3/blob-csi-driver/templates/_helpers.tpl
  charts/v1.19.3/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.19.3/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.19.3/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.19.3/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.19.3/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.19.3/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.19.3/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.19.3/blob-csi-driver/values.yaml
  charts/v1.20.2/blob-csi-driver-v1.20.2.tgz
  charts/v1.20.2/blob-csi-driver/Chart.yaml
  charts/v1.20.2/blob-csi-driver/templates/NOTES.txt
  charts/v1.20.2/blob-csi-driver/templates/_helpers.tpl
  charts/v1.20.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.20.2/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.20.2/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.20.2/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.20.2/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.20.2/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.20.2/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.20.2/blob-csi-driver/values.yaml
  deploy/v1.19.3/csi-blob-controller.yaml
  deploy/v1.19.3/csi-blob-driver.yaml
  deploy/v1.19.3/csi-blob-node.yaml
  deploy/v1.19.3/kustomization.yaml
  deploy/v1.19.3/rbac-csi-blob-controller.yaml
  deploy/v1.19.3/rbac-csi-blob-node.yaml
  deploy/v1.20.2/csi-blob-controller.yaml
  deploy/v1.20.2/csi-blob-driver.yaml
  deploy/v1.20.2/csi-blob-node.yaml
  deploy/v1.20.2/kustomization.yaml
  deploy/v1.20.2/rbac-csi-blob-controller.yaml
  deploy/v1.20.2/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.19.3.md
  docs/install-csi-driver-v1.20.2.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#879 fix: increase mount timeout check as 60s
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#882 doc: cut v1.21.0 release
  README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.21.0/blob-csi-driver-v1.21.0.tgz
  charts/v1.21.0/blob-csi-driver/Chart.yaml
  charts/v1.21.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.21.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.21.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.21.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.21.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.21.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.21.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.21.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.21.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.21.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.21.0/csi-blob-controller.yaml
  deploy/v1.21.0/csi-blob-driver.yaml
  deploy/v1.21.0/csi-blob-node.yaml
  deploy/v1.21.0/kustomization.yaml
  deploy/v1.21.0/rbac-csi-blob-controller.yaml
  deploy/v1.21.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.21.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#887 cleanup: replace deprecated ioutil method
  pkg/blob/azure_test.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
Labels: size/S, approved, cncf-cla: yes, lgtm, ok-to-test, kind/cleanup

#893 fix: mount failure when mountOptions is empty
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/server/server.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M

#894 doc: fix docs for blobfuse proxy
  deploy/blobfuse-proxy/README.md
  deploy/blobfuse-proxy/v0.1.0/blobfuse-proxy-v0.1.0.deb
  deploy/blobfuse-proxy/v0.1.1/blobfuse-proxy.deb
  pkg/blobfuse-proxy/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#892 fix: install blobfuse package issue in blobfuse-proxy initContainer
  pkg/blobfuse-proxy/init.sh
  pkg/blobplugin/Dockerfile
Labels: size/S, approved, cncf-cla: yes, lgtm
