Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-11, with the labels that each got.

#1085 feat: install blobfuse 2.1.1 as default version
  .trivyignore
  README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  docs/csi-debug.md
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1088 doc: add ZRS storage sku in the doc
  deploy/example/storageclass-blobfuse.yaml
  deploy/example/storageclass-blobfuse2.yaml
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1093 cleanup: update azcopy 10.21.2
  .trivyignore
  pkg/blobplugin/Dockerfile
Labels: size/S, cncf-cla: yes, ok-to-test, kind/cleanup

#1045 feat: support blobfuse-proxy on OpenShift
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/install-proxy-mariner.sh
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy-ubuntu.sh
  pkg/blobfuse-proxy/server/server.go
  pkg/blobplugin/Dockerfile
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1090 feat: switch to bookworm debian base image
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS, lgtm

#1103 fix: make aznfs protocol consistent with nfs
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1094 Refactor: adopt dependency injection pattern and extract cloud property
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver_test.go
  pkg/blobplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, kind/cleanup, size/L

#1104 [release-1.23] feat: support blobfuse-proxy on OpenShift
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/install-proxy-mariner.sh
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy-ubuntu.sh
  pkg/blobfuse-proxy/server/server.go
  pkg/blobplugin/Dockerfile
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, size/L

#1110 [release-1.22] fix: make aznfs protocol consistent with nfs
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1102 [release-1.23] feat: use azcopy for volume cloning
  deploy/csi-blob-controller.yaml
  deploy/example/pvc-blob-csi-clone.yaml
  hack/boilerplate/boilerplate.generatego.txt
  hack/boilerplate/boilerplate.gomock.txt
  hack/boilerplate/boilerplate.py
  hack/update-mock.sh
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/main.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/utils_test.go
  pkg/util/util.go
  pkg/util/util_mock.go
  pkg/util/util_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
  test/e2e/testsuites/specs.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver-blobfuse.yaml
  test/external-e2e/testdriver-nfs.yaml
  test/sanity/run-test.sh
Labels: kind/feature, size/XXL, cncf-cla: yes, ok-to-test

#1108 [release-1.21] feat: switch to bookworm debian base image
  pkg/blobplugin/Dockerfile
Labels: cncf-cla: yes, size/XS

#1107 [release-1.22] feat: switch to bookworm debian base image
  pkg/blobplugin/Dockerfile
Labels: cncf-cla: yes, size/XS

#1105 [release-1.23] feat: switch to bookworm debian base image
  pkg/blobplugin/Dockerfile
Labels: cncf-cla: yes, size/XS

#1112 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1111 doc: add aznfs mount helper tsg
  docs/csi-debug.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#1115 feat: install blobfuse 2.1.2 as default version
  README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  docs/csi-debug.md
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1117 [release-1.22] fix: CVE-2023-5528
  go.mod
  go.sum
  vendor/github.com/google/cel-go/checker/cost.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/string_array_flag.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/structuredmerge.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/cel/library/cost.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/endpoints/installer.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/apiserver/pkg/server/secure_serving.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/kubernetes/pkg/apis/batch/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/wait.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1118 [release-1.21] fix: CVE-2023-5528
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/string_array_flag.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1116 [release-1.23] fix: CVE-2023-5528
  go.mod
  go.sum
  vendor/github.com/google/cel-go/checker/cost.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/cel/library/cost.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go
  vendor/k8s.io/apiserver/pkg/server/secure_serving.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/kubernetes/pkg/apis/batch/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/wait.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XL

#1119 test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/fake_mount.go
  pkg/blob/identityserver.go
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/server/server.go
  pkg/blobplugin/main.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/server_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/driver/blob_csi_driver.go
  test/e2e/testsuites/dynamically_provisioned_inline_volume.go
  test/e2e/testsuites/specs.go
Labels: kind/test, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1120 doc: update blobfuse-proxy support on coreos
  charts/README.md
  deploy/blobfuse-proxy/README.md
  docs/install-csi-driver-master.md
Labels: size/S, approved, cncf-cla: yes, kind/documentation

#1129 doc: add volume cloning doc
  README.md
  deploy/example/cloning/README.md
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/cloning/pvc-blob-csi-cloning.yaml
  hack/verify-yamllint.sh
Labels: cncf-cla: yes, kind/documentation, size/M, ok-to-test

#1132 cleanup: update new chart versions
  README.md
  charts/index.yaml
  charts/v1.21.6/blob-csi-driver-v1.21.6.tgz
  charts/v1.21.6/blob-csi-driver/Chart.yaml
  charts/v1.21.6/blob-csi-driver/templates/NOTES.txt
  charts/v1.21.6/blob-csi-driver/templates/_helpers.tpl
  charts/v1.21.6/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.21.6/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.21.6/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.21.6/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.21.6/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.21.6/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.21.6/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.21.6/blob-csi-driver/values.yaml
  charts/v1.22.4/blob-csi-driver-v1.22.4.tgz
  charts/v1.22.4/blob-csi-driver/Chart.yaml
  charts/v1.22.4/blob-csi-driver/templates/NOTES.txt
  charts/v1.22.4/blob-csi-driver/templates/_helpers.tpl
  charts/v1.22.4/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.22.4/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.22.4/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.22.4/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.22.4/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.22.4/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.22.4/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.22.4/blob-csi-driver/values.yaml
  charts/v1.23.2/blob-csi-driver-v1.23.2.tgz
  charts/v1.23.2/blob-csi-driver/Chart.yaml
  charts/v1.23.2/blob-csi-driver/templates/NOTES.txt
  charts/v1.23.2/blob-csi-driver/templates/_helpers.tpl
  charts/v1.23.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.2/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.23.2/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.23.2/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.23.2/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.23.2/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.23.2/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.23.2/blob-csi-driver/values.yaml
  deploy/v1.21.6/csi-blob-controller.yaml
  deploy/v1.21.6/csi-blob-driver.yaml
  deploy/v1.21.6/csi-blob-node.yaml
  deploy/v1.21.6/kustomization.yaml
  deploy/v1.21.6/rbac-csi-blob-controller.yaml
  deploy/v1.21.6/rbac-csi-blob-node.yaml
  deploy/v1.22.4/csi-blob-controller.yaml
  deploy/v1.22.4/csi-blob-driver.yaml
  deploy/v1.22.4/csi-blob-node.yaml
  deploy/v1.22.4/kustomization.yaml
  deploy/v1.22.4/rbac-csi-blob-controller.yaml
  deploy/v1.22.4/rbac-csi-blob-node.yaml
  deploy/v1.23.2/csi-blob-controller.yaml
  deploy/v1.23.2/csi-blob-driver.yaml
  deploy/v1.23.2/csi-blob-node.yaml
  deploy/v1.23.2/kustomization.yaml
  deploy/v1.23.2/rbac-csi-blob-controller.yaml
  deploy/v1.23.2/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.21.6.md
  docs/install-csi-driver-v1.22.4.md
  docs/install-csi-driver-v1.23.2.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1131 doc: add nconnect mount option in the doc
  deploy/example/nfs/README.md
  deploy/example/pv-blobfuse-nfs.yaml
  deploy/example/storageclass-blob-nfs.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1137 feat: install blobfuse 2.1.2 as default version on v1.23.1, v1.22.3
  charts/v1.22.3/blob-csi-driver-v1.22.3.tgz
  charts/v1.22.3/blob-csi-driver/values.yaml
  charts/v1.23.1/blob-csi-driver-v1.23.1.tgz
  charts/v1.23.1/blob-csi-driver/values.yaml
  deploy/v1.22.3/csi-blob-node.yaml
  deploy/v1.23.1/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1138 [release-1.23] feat: install blobfuse 2.1.2 as default version
  README.md
  charts/latest/blob-csi-driver-v1.23.2.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.2/blob-csi-driver-v1.23.2.tgz
  charts/v1.23.2/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  docs/csi-debug.md
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1139 doc: fix readOnly setting doc
  deploy/example/e2e_usage.md
  deploy/example/nginx-blobfuse-inline-volume.yaml
  deploy/example/nginx-pod-blob.yaml
  deploy/example/pv-blobfuse-auth.yaml
  deploy/example/pv-blobfuse-csi-keyvault.yaml
  deploy/example/pv-blobfuse-csi.yaml
  deploy/example/pv-blobfuse-nfs.yaml
  deploy/example/statefulset-nfs.yaml
  deploy/example/statefulset-nonroot-nfs.yaml
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset.yaml
Labels: size/S, approved, cncf-cla: yes, kind/documentation

#1144 chore(deps): bump k8s.io/klog/v2 from 2.100.1 to 2.110.1
  go.mod
  go.sum
  pkg/blobfuse-proxy/main.go
  vendor/github.com/go-logr/logr/slogr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/go-logr/logr/slogr/slogsink.go
  vendor/k8s.io/klog/v2/.golangci.yaml
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go
  vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go
  vendor/k8s.io/klog/v2/k8s_references_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test, kind/cleanup
