Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#834 tes: fix golint action failure
  .github/workflows/static.yaml
  go.mod
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: size/S, approved, cncf-cla: yes, kind/failing-test

#842 fix: add workaround for blobfuse2 mount race condition issue
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/server/server.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#851 doc: update supported version and cleanup deprecated versions
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.19.0/blob-csi-driver-v1.19.0.tgz
  charts/v1.19.2/blob-csi-driver-v1.19.2.tgz
  charts/v1.19.2/blob-csi-driver/Chart.yaml
  charts/v1.19.2/blob-csi-driver/templates/NOTES.txt
  charts/v1.19.2/blob-csi-driver/templates/_helpers.tpl
  charts/v1.19.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.19.2/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.19.2/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.19.2/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.19.2/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.19.2/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.19.2/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.19.2/blob-csi-driver/values.yaml
  charts/v1.20.0/blob-csi-driver-v1.20.0.tgz
  charts/v1.20.1/blob-csi-driver-v1.20.1.tgz
  charts/v1.20.1/blob-csi-driver/Chart.yaml
  charts/v1.20.1/blob-csi-driver/templates/NOTES.txt
  charts/v1.20.1/blob-csi-driver/templates/_helpers.tpl
  charts/v1.20.1/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.20.1/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.20.1/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.20.1/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.20.1/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.20.1/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.20.1/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.20.1/blob-csi-driver/values.yaml
  deploy/v1.19.2/csi-blob-controller.yaml
  deploy/v1.19.2/csi-blob-driver.yaml
  deploy/v1.19.2/csi-blob-node.yaml
  deploy/v1.19.2/kustomization.yaml
  deploy/v1.19.2/rbac-csi-blob-controller.yaml
  deploy/v1.19.2/rbac-csi-blob-node.yaml
  deploy/v1.20.1/csi-blob-controller.yaml
  deploy/v1.20.1/csi-blob-driver.yaml
  deploy/v1.20.1/csi-blob-node.yaml
  deploy/v1.20.1/kustomization.yaml
  deploy/v1.20.1/rbac-csi-blob-controller.yaml
  deploy/v1.20.1/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.19.2.md
  docs/install-csi-driver-v1.20.1.md
Labels: approved, cncf-cla: yes, kind/documentation, size/L

#853 test: fix capz test failure
  Makefile
Labels: approved, cncf-cla: yes, size/M, kind/failing-test

#852 fix: wait to make sure blobfuse mount complete before bind mount
  go.mod
  go.sum
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/blobfuse-proxy/server/server.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_generic.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/L
