Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#947 doc: cut v1.22.0 release
  README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.22.0/blob-csi-driver-v1.22.0.tgz
  charts/v1.22.0/blob-csi-driver/Chart.yaml
  charts/v1.22.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.22.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.22.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.22.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.22.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.22.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.22.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.22.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.22.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.22.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.22.0/csi-blob-controller.yaml
  deploy/v1.22.0/csi-blob-driver.yaml
  deploy/v1.22.0/csi-blob-node.yaml
  deploy/v1.22.0/kustomization.yaml
  deploy/v1.22.0/rbac-csi-blob-controller.yaml
  deploy/v1.22.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.22.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#952 chore: fix uninstall-driver to make it backward compatibility
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, size/XS, lgtm

#954 fix: dynamic provisioning support with blobfuse msi auth
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/L

#957 [release-1.22] fix: dynamic provisioning support with blobfuse msi auth
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#955 [release-1.21] fix: dynamic provisioning support with blobfuse msi auth
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#960 cleanup: update new chart versions and remove deprecated versions
  README.md
  charts/index.yaml
  charts/v1.21.3/blob-csi-driver-v1.21.3.tgz
  charts/v1.21.4/blob-csi-driver-v1.21.4.tgz
  charts/v1.21.4/blob-csi-driver/Chart.yaml
  charts/v1.21.4/blob-csi-driver/templates/NOTES.txt
  charts/v1.21.4/blob-csi-driver/templates/_helpers.tpl
  charts/v1.21.4/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.21.4/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.21.4/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.21.4/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.21.4/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.21.4/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.21.4/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.21.4/blob-csi-driver/values.yaml
  deploy/v1.21.4/csi-blob-controller.yaml
  deploy/v1.21.4/csi-blob-driver.yaml
  deploy/v1.21.4/csi-blob-node.yaml
  deploy/v1.21.4/kustomization.yaml
  deploy/v1.21.4/rbac-csi-blob-controller.yaml
  deploy/v1.21.4/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.21.4.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M
