Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#1146 fix: modprobe command error with aznfs mount
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  pkg/blobplugin/Dockerfile
Labels: kind/bug, approved, cncf-cla: yes, size/XS, lgtm

#1149 [release-1.22] fix: modprobe command error with aznfs mount
  charts/latest/blob-csi-driver-v1.22.4.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  pkg/blobplugin/Dockerfile
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1148 [release-1.23] fix: modprobe command error with aznfs mount
  charts/latest/blob-csi-driver-v1.23.2.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  pkg/blobplugin/Dockerfile
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1151 chore: support installing blob-csi-driver with aznfs-mount by install-driver.sh
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#1154 feat: install blobfuse 2.1.2 as default version on v1.22.4, v1.23.2
  charts/v1.22.4/blob-csi-driver-v1.22.4.tgz
  charts/v1.22.4/blob-csi-driver/values.yaml
  charts/v1.23.2/blob-csi-driver-v1.23.2.tgz
  charts/v1.23.2/blob-csi-driver/values.yaml
  deploy/v1.22.4/csi-blob-node.yaml
  deploy/v1.23.2/csi-blob-node.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1155 chore: support deploy aznfs mount helper in v1.22 and v1.23
  deploy/v1.22.4/csi-blob-node.yaml
  deploy/v1.23.2/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1157 doc: fix storage identity typo
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#1159 feat: upgrade to aznfs 2.0.0 version for nfs mount
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS, lgtm

#1164 Refactor: Extract kubeclient from cloud provider
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver_test.go
  pkg/blobplugin/main.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/L

#1165 test: add more external e2e tests
  test/external-e2e/testdriver-blobfuse.yaml
  test/external-e2e/testdriver-nfs.yaml
Labels: kind/test, approved, cncf-cla: yes, size/XS

#1176 feat: upgrade to aznfs 2.0.1 version for nfs mount
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1179 [release-1.22] test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/fake_mount.go
  pkg/blob/identityserver.go
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/server/server.go
  pkg/blobplugin/main.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/server_test.go
  pkg/util/util_test.go
  test/e2e/driver/blob_csi_driver.go
  test/e2e/testsuites/dynamically_provisioned_inline_volume.go
  test/e2e/testsuites/specs.go
  test/utils/azure/azure_helper.go
Labels: kind/test, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1180 fix: CVE-2023-48795
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1184 doc: fix volume cloning doc
  deploy/example/cloning/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1185 [release-1.21] test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/fake_mount.go
  pkg/blob/identityserver.go
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/server/server.go
  pkg/blobplugin/main.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/server_test.go
  pkg/util/util_test.go
  test/e2e/driver/blob_csi_driver.go
  test/e2e/testsuites/dynamically_provisioned_inline_volume.go
  test/e2e/testsuites/specs.go
  test/utils/azure/azure_helper.go
Labels: kind/test, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1187 Refactor: remove grpc wrapper
  go.mod
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blobplugin/main.go
  pkg/csi-common/server.go
  pkg/csi-common/server_test.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1190 feat: upgrade azcopy to v10.22.1 for volume clone feature
  .trivyignore
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1192 test: always use latest azcopy version in sanity test
  test/sanity/run-test.sh
Labels: kind/test, size/S, approved, cncf-cla: yes

#1193 fix: reduce mount lock to avoid volumeID collision issue
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1196 fix: mountPermission settting issue due to case insensitive parameter
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/M
