Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-02, with the labels that each got.

#820 fix: buildx issue with provenance disabled
  Makefile
  hack/boilerplate/boilerplate.py
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#821 chore: remove dependency on golang.org/x/text specific version
  go.mod
  go.sum
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/runes/runes.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, size/M, kind/cleanup

#822 feat: append help link when there is mount error
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  pkg/blobplugin/main.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#823 fix: CVE-2022-41723
  go.mod
  go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.c
  vendor/golang.org/x/sys/cpu/endian_big.go
  vendor/golang.org/x/sys/cpu/endian_little.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XL

#825 Update debian-base image to v1.4.3
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test, kind/cleanup

#826 cleanup: remove metrics-address on driver daemonset on the node
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobplugin/main.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#827 fix: mount failed on ubuntu 22.04(aks 1.25.2)
  pkg/blobfuse-proxy/server/server.go
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#828 doc: cut v1.20.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.20.0/blob-csi-driver-v1.20.0.tgz
  charts/v1.20.0/blob-csi-driver/Chart.yaml
  charts/v1.20.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.20.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.20.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.20.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.20.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.20.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.20.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.20.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.20.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.20.0/blob-csi-driver/values.yaml
  deploy/blobfuse-proxy/README.md
  deploy/v1.20.0/csi-blob-controller.yaml
  deploy/v1.20.0/csi-blob-driver.yaml
  deploy/v1.20.0/csi-blob-node.yaml
  deploy/v1.20.0/kustomization.yaml
  deploy/v1.20.0/rbac-csi-blob-controller.yaml
  deploy/v1.20.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.20.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#830 [release-1.19] fix: mount failed on ubuntu 22.04(aks 1.25.2)
  Makefile
  hack/boilerplate/boilerplate.py
  pkg/blobfuse-proxy/server/server.go
  test/external-e2e/run.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes
