Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#1001 feat: install blobfuse 2.1.0 as default version
  README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  docs/csi-debug.md
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1006 [release 1.22] feat: support aznfs mount helper
  Makefile
  charts/README.md
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/init.sh
  pkg/blobplugin/Dockerfile
  pkg/blobplugin/main.go
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1008 feat: enable HonorPVReclaimPolicy in csi-provisioner
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1009 doc: update volumeHandle doc
  deploy/example/e2e_usage.md
  deploy/example/pv-blobfuse-auth.yaml
  deploy/example/pv-blobfuse-csi-keyvault.yaml
  deploy/example/pv-blobfuse-csi.yaml
  deploy/example/pv-blobfuse-nfs.yaml
  docs/driver-parameters.md
Labels: size/S, approved, cncf-cla: yes, kind/documentation

#1010 chore: set enable-aznfs-mount default value as false
  pkg/blobplugin/main.go
Labels: approved, cncf-cla: yes, size/XS, lgtm, kind/cleanup

#1013 fix: match account if PrivateEndpoint is not set in storage class
  go.mod
  go.sum
  pkg/blob/controllerserver.go
  vendor/k8s.io/cloud-provider/api/retry_error.go
  vendor/k8s.io/cloud-provider/api/well_known_annotations.go
  vendor/k8s.io/cloud-provider/api/well_known_taints.go
  vendor/k8s.io/cloud-provider/node/helpers/address.go
  vendor/k8s.io/cloud-provider/node/helpers/labels.go
  vendor/k8s.io/cloud-provider/node/helpers/taints.go
  vendor/k8s.io/component-helpers/node/util/cidr.go
  vendor/k8s.io/component-helpers/node/util/conditions.go
  vendor/k8s.io/component-helpers/node/util/hostname.go
  vendor/k8s.io/component-helpers/node/util/ips.go
  vendor/k8s.io/component-helpers/node/util/status.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/helpers.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_privatelinkservice.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/util/taints/taints.go
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1014 cleanup: update new chart versions and remove deprecated versions
  README.md
  charts/index.yaml
  charts/v1.22.2/blob-csi-driver-v1.22.2.tgz
  charts/v1.22.2/blob-csi-driver/Chart.yaml
  charts/v1.22.2/blob-csi-driver/templates/NOTES.txt
  charts/v1.22.2/blob-csi-driver/templates/_helpers.tpl
  charts/v1.22.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.22.2/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.22.2/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.22.2/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.22.2/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.22.2/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.22.2/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.22.2/blob-csi-driver/values.yaml
  deploy/v1.22.2/csi-blob-controller.yaml
  deploy/v1.22.2/csi-blob-driver.yaml
  deploy/v1.22.2/csi-blob-node.yaml
  deploy/v1.22.2/kustomization.yaml
  deploy/v1.22.2/rbac-csi-blob-controller.yaml
  deploy/v1.22.2/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.22.2.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1016 fix: add VolumeStats cache to avoid massive statfs calls
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
  pkg/blobplugin/main.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1018 [release-1.21] fix: add VolumeStats cache to avoid massive statfs calls
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1019 doc: cut v1.23.0 release
  README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.23.0/blob-csi-driver-v1.23.0.tgz
  charts/v1.23.0/blob-csi-driver/Chart.yaml
  charts/v1.23.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.23.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.23.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.23.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.23.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.23.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.23.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.23.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.23.0/blob-csi-driver/values.yaml
  deploy/v1.23.0/csi-blob-controller.yaml
  deploy/v1.23.0/csi-blob-driver.yaml
  deploy/v1.23.0/csi-blob-node.yaml
  deploy/v1.23.0/kustomization.yaml
  deploy/v1.23.0/rbac-csi-blob-controller.yaml
  deploy/v1.23.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.23.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1023 fix: refine create volume metrics
  pkg/blob/controllerserver.go
Labels: size/S, approved, cncf-cla: yes, kind/cleanup
