Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2023-05, with the labels that each got.

#899 chore: upgrade csi sidecar container images
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#898 feat: install blobfuse 2.0.3 by default
  README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#902 [release-1.19] feat: support install specific blobfuse version using blobfuse-proxy
  charts/README.md
  charts/latest/blob-csi-driver-v1.19.4.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  test/utils/blob_log.sh
Labels: kind/feature, approved, size/M

#903 [release-1.20] feat: support install specific blobfuse version using blobfuse-proxy
  README.md
  charts/README.md
  charts/latest/blob-csi-driver-v1.20.3.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  test/utils/blob_log.sh
Labels: kind/feature, approved, cncf-cla: yes, size/M

#909 [release-1.20] fix: mount failure when mountOptions is empty
  pkg/blob/nodeserver.go
  pkg/blobfuse-proxy/server/server.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#910 doc: cut v1.20.3 release
  charts/index.yaml
  charts/latest/blob-csi-driver-v1.20.3.tgz
  charts/v1.20.3/blob-csi-driver-v1.20.3.tgz
  charts/v1.20.3/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.20.3/blob-csi-driver/values.yaml
  deploy/v1.20.3/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#918 feat: add fsGroupPolicy parameter in helm chart
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-driver.yaml
  deploy/example/fsgroup/README.md
  test/external-e2e/run.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#921 test: run nonroot pod test on blobfuse2 mount
  hack/verify-examples.sh
Labels: kind/test, approved, cncf-cla: yes, size/XS

#924 feat: support workload identity
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  docs/workload-identity.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#927 fix: msi auth issue when secret is not provided
  pkg/blob/blob.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#932 fix: use dl.k8s.io, not kubernetes-release bucket
  test/external-e2e/run.sh
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup

#934 cleanup: update new chart versions and remove deprecated versions
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.21.2/blob-csi-driver-v1.21.2.tgz
  charts/v1.21.2/blob-csi-driver/Chart.yaml
  charts/v1.21.2/blob-csi-driver/templates/NOTES.txt
  charts/v1.21.2/blob-csi-driver/templates/_helpers.tpl
  charts/v1.21.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.21.2/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.21.2/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.21.2/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.21.2/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.21.2/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.21.2/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.21.2/blob-csi-driver/values.yaml
  deploy/v1.21.2/csi-blob-controller.yaml
  deploy/v1.21.2/csi-blob-driver.yaml
  deploy/v1.21.2/csi-blob-node.yaml
  deploy/v1.21.2/kustomization.yaml
  deploy/v1.21.2/rbac-csi-blob-controller.yaml
  deploy/v1.21.2/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.19.5.md
  docs/install-csi-driver-v1.21.2.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#936 build: add dependabot job for dockerfile updates
  .github/dependabot.yaml
Labels: kind/test, size/S, approved, cncf-cla: yes, lgtm

#938 doc: refine workload identity doc
  README.md
  docs/workload-identity.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#942 feat: support setting AzureStorageSPNClientID/TenantId in secret
  docs/driver-parameters.md
  pkg/blob/blob.go
  pkg/blob/blob_test.go
Labels: kind/feature, approved, cncf-cla: yes, size/M
