Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-09, with the labels that each got.

#1564 fix: add fallback to sas token on azcopy copy command
  deploy/example/storageclass-blob-nfs.yaml
  deploy/example/storageclass-blobfuse.yaml
  deploy/example/storageclass-blobfuse2.yaml
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  test/external-e2e/run.sh
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1568 [release-1.23] fix: add fallback to sas token on azcopy copy command
  deploy/example/storageclass-blob-nfs.yaml
  deploy/example/storageclass-blobfuse.yaml
  deploy/example/storageclass-blobfuse2.yaml
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  test/external-e2e/run.sh
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1569 fix: CVE-2024-38428 remove wget to close vuln, reduce image size
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1570 cleanup: fix golint errors
  .github/workflows/static.yaml
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1575 chore: upgrade to debian-base:bookworm-v1.0.4 base image
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1576 feat: install blobfuse 2.3.2 as default version
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.7/blob-csi-driver-v1.23.7.tgz
  charts/v1.23.7/blob-csi-driver/values.yaml
  charts/v1.24.3/blob-csi-driver-v1.24.3.tgz
  charts/v1.24.3/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.7/csi-blob-node.yaml
  deploy/v1.24.3/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1581 [release-1.23] feat: install blobfuse 2.3.2 as default version
  charts/latest/blob-csi-driver-v1.23.7.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.7/blob-csi-driver-v1.23.7.tgz
  charts/v1.23.7/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.7/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1580 [release-1.24] feat: install blobfuse 2.3.2 as default version
  charts/latest/blob-csi-driver-v1.24.3.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.24.3/blob-csi-driver-v1.24.3.tgz
  charts/v1.24.3/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.24.3/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1579 [release-1.22] chore: upgrade to debian-base:bookworm-v1.0.4 base image
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1583 chore: upgrade golang version
  .github/workflows/trivy.yaml
  .trivyignore
  go.mod
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1590 doc: update inline volume doc
  deploy/example/e2e_usage.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1589 [release-1.23] chore: upgrade golang version
  .github/workflows/trivy.yaml
  .trivyignore
  go.mod
  pkg/blob/controllerserver_test.go
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
Labels: size/S, approved, cncf-cla: yes, kind/failing-test

#1593 [release-1.23] cleanup: fix golint error
  go.mod
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1592 [release-1.22] cleanup: fix golint error
  go.mod
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1594 fix: upgrade node-driver-registrar to fix register timeout issue
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
  charts/v1.23.4/blob-csi-driver/values.yaml
  charts/v1.23.7/blob-csi-driver-v1.23.7.tgz
  charts/v1.23.7/blob-csi-driver/values.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/values.yaml
  charts/v1.24.2/blob-csi-driver-v1.24.2.tgz
  charts/v1.24.2/blob-csi-driver/values.yaml
  charts/v1.24.3/blob-csi-driver-v1.24.3.tgz
  charts/v1.24.3/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.4/csi-blob-node.yaml
  deploy/v1.23.7/csi-blob-node.yaml
  deploy/v1.24.1/csi-blob-node.yaml
  deploy/v1.24.2/csi-blob-node.yaml
  deploy/v1.24.3/csi-blob-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1596 [release-1.23] fix: upgrade node-driver-registrar to fix register timeout issue
  charts/README.md
  charts/latest/blob-csi-driver-v1.23.7.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
  charts/v1.23.4/blob-csi-driver/values.yaml
  charts/v1.23.7/blob-csi-driver-v1.23.7.tgz
  charts/v1.23.7/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.4/csi-blob-node.yaml
  deploy/v1.23.7/csi-blob-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1595 [release-1.24] fix: upgrade node-driver-registrar to fix register timeout issue
  charts/README.md
  charts/latest/blob-csi-driver-v1.24.3.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/values.yaml
  charts/v1.24.2/blob-csi-driver-v1.24.2.tgz
  charts/v1.24.2/blob-csi-driver/values.yaml
  charts/v1.24.3/blob-csi-driver-v1.24.3.tgz
  charts/v1.24.3/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.24.1/csi-blob-node.yaml
  deploy/v1.24.2/csi-blob-node.yaml
  deploy/v1.24.3/csi-blob-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1600 [release-1.22] cleanup: upgrade golint version and fix golint errors
  .github/workflows/static.yaml
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  pkg/csi-common/utils_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1602 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1605 [release-1.23] chore: upgrade sidecar image versions
  charts/latest/blob-csi-driver-v1.23.7.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1601 [release-1.23] cleanup: upgrade golint version and fix golint errors
  .github/workflows/static.yaml
  hack/verify-golint.sh
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, size/M, ok-to-test

#1604 [release-1.24] chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/blob-csi-driver-v1.24.3.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1607 fix: inherit os environment when calling blobfuse2 in blobfuse-proxy
  pkg/blobfuse-proxy/server/server.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS
