Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#1526 [release-1.23] feat: upgrade to azcopy v10.26.0 for volume clone and snapshot restore
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1525 [release-1.24] feat: upgrade to azcopy v10.26.0 for volume clone and snapshot restore
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1524 feat: upgrade to azcopy v10.26.0 for volume clone and snapshot restore
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1521 cleanup: refactor volume cloning
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, kind/cleanup, size/L

#1520 [release-1.23] fix: clone volume content to requested volume
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/volume_lock.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1534 fix: only last subnet is set in account ACL created by driver
  pkg/blob/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1533 fix: respect ReadOnly AccessMode in volume mount
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1539 doc: improve volume cloning doc
  deploy/example/cloning/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS, lgtm, ok-to-test

#1538 fix: nfs mount failure when there are multiple subnets in the cluster
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1541 fix: VirtualNetworkRule match issue during account search
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1542 [release-1.24] fix: VirtualNetworkRule match issue during account search
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1550 fix: volume cloning sas token logged
  pkg/blob/controllerserver.go
Labels: kind/bug, cncf-cla: yes, size/XS, ok-to-test

#1551 test: use wi for e2e test
  deploy/example/storageclass-blob-nfs.yaml
  deploy/example/storageclass-blobfuse.yaml
  deploy/example/storageclass-blobfuse2.yaml
  go.mod
  go.sum
  hack/verify-examples.sh
  pkg/util/util.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/external-e2e/run.sh
  test/sanity/run-test.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helper.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/SECURITY.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test

#1559 [release-1.23] test: use workload identity for e2e test
  deploy/example/storageclass-blob-nfs.yaml
  deploy/example/storageclass-blobfuse.yaml
  deploy/example/storageclass-blobfuse2.yaml
  go.mod
  go.sum
  hack/verify-examples.sh
  pkg/util/util.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/external-e2e/run.sh
  test/integration/README.md
  test/integration/integration_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
  test/sanity/run-test.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helper.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/SECURITY.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, kind/failing-test

#1563 [release-1.23] cleanup: refactor volume cloning
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, kind/cleanup, size/L

#1554 chore: Replace deprecated k8s.io/utils/pointer with k8s.io/utils/ptr
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/controllerserver.go
  test/e2e/testsuites/testsuites.go
  test/utils/azure/authorization_helper.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test
