Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#1200 [release-1.23] feat: use cluster identity for using azcopy in volume cloning
  deploy/example/cloning/README.md
  hack/update-mock.sh
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/util/util.go
  pkg/util/util_mock.go
  pkg/util/util_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1201 cleanup: add cache in sastoken fallback
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1199 feat: support volume mount group and add FSGroupChangePolicy param for NFS mount
  docs/driver-parameters.md
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/dynamic_provisioning_test.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver-blobfuse.yaml
  test/external-e2e/testdriver-nfs.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1203 feat: upgrade to aznfs 2.0.3 version for nfs mount
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1207 fix: generate sas token when secret is used in volume cloning
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1208 [release-1.23] fix: generate sas token when secret is used in volume cloning
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1204 feat: support workload identity setting in static PV mount
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-driver.yaml
  docs/workload-identity-deploy-csi-driver.md
  docs/workload-identity-static-pv-mount.md
  go.mod
  go.sum
  pkg/blob/blob.go
  pkg/blob/nodeserver.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_healthprobe.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, tide/merge-method-squash, size/L

#1210 chore: Update workload-identity-static-pv-mount.md
  docs/workload-identity-static-pv-mount.md
Labels: approved, cncf-cla: yes, size/XS, lgtm

#1214 chore: fix ut
  pkg/blob/azure_test.go
Labels: kind/test, approved, cncf-cla: yes, lgtm, size/M

#1219 feat: upgrade azcopy version to 10.22.2
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1218 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1220 [release-1.23] feat: upgrade azcopy version to 10.22.2 for volume clone feature
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1169 Refactor: migrate blobclient to track2 sdk and fix ut cases
  go.mod
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/accountclient/mock_accountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobcontainerclient/mock_blobcontainerclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1226 fix: increase volume cloning timeout and reduce time cost
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/M
