Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-06, with the labels that each got.

#1409 feat: upgrade to azcopy v10.25.0 for volume clone feature
  .github/workflows/codespell.yml
  .github/workflows/trivy.yaml
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1414 [release-1.22] test: fix trivy and codespell error
  .github/workflows/codespell.yml
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1416 [release-1.23] feat: install blobfuse 2.3.0 as default version
  charts/latest/blob-csi-driver-v1.23.4.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
  charts/v1.23.4/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.4/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1417 [release-1.24] feat: install blobfuse 2.3.0 as default version
  charts/latest/blob-csi-driver-v1.24.1.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.24.1/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1420 fix: CVE-2024-35255
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/async/async.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/body/body.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/fake/fake.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/loc/loc.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/op/op.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/util.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/pager.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/request.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/.gitignore
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/MIGRATION.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TOKEN_CACHING.MD
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_pipelines_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/chained_token_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_assertion_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_certificate_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/confidential_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/developer_credential_util.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/device_code_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/environment_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/go.work.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/interactive_browser_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed-identity-matrix.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/on_behalf_of_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/public_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-pre.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1424 fix: shield guard issues
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes, lgtm, ok-to-test

#1428 chore: use go 1.22 in go.mod
  go.mod
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1429 feat: upgrade to azcopy v10.25.1 for volume clone feature
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1432 cleanup: remove .trivyignore file
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#1433 fix: shield guard issues in latest 2 versions
  charts/v1.22.6/blob-csi-driver-v1.22.6.tgz
  charts/v1.22.6/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
  deploy/v1.22.6/csi-blob-controller.yaml
  deploy/v1.24.1/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1434 fix: shield guard issues on node
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.22.6/blob-csi-driver-v1.22.6.tgz
  charts/v1.22.6/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.22.6/csi-blob-node.yaml
  deploy/v1.24.1/csi-blob-node.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1435 feat: upgrade to aznfs 2.0.7 version for nfs mount
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1441 [release-1.23] fix shield guard on csi controller and node
  charts/latest/blob-csi-driver-v1.23.5.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1442 [release-1.24] fix shield guard on csi controller and node
  charts/latest/blob-csi-driver-v1.24.1.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1443 chore: fix workload identity docs
  docs/workload-identity-static-pv-mount.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1425 fix: force copy blobfuse2 binary to avoid Text file busy error
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes, lgtm

#1440 [release-1.22] fix shield guard on csi controller and node
  charts/latest/blob-csi-driver-v1.22.6.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1439 fix: override aznfs AZURE_ENDPOINT_OVERRIDE
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1448 [release-1.23] fix: force copy blobfuse2 binary to avoid Text file busy error
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: size/S, cncf-cla: yes

#1451 [release-1.23] chore: upgrade CSI driver sidecar image versions
  charts/latest/blob-csi-driver-v1.23.5.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
  charts/v1.23.4/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.4/csi-blob-controller.yaml
  deploy/v1.23.4/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1449 chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
  charts/v1.23.4/blob-csi-driver/values.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.4/csi-blob-controller.yaml
  deploy/v1.23.4/csi-blob-node.yaml
  deploy/v1.24.1/csi-blob-controller.yaml
  deploy/v1.24.1/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1450 [release-1.24] chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/blob-csi-driver-v1.24.1.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.24.1/csi-blob-controller.yaml
  deploy/v1.24.1/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1454 fix: add azcopy-dir since volume cloning supported from v1.23.2
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.2/blob-csi-driver-v1.23.2.tgz
  charts/v1.23.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.3/blob-csi-driver-v1.23.3.tgz
  charts/v1.23.3/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
  charts/v1.23.4/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.0/blob-csi-driver-v1.24.0.tgz
  charts/v1.24.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
  charts/v1.24.1/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
  deploy/v1.23.2/csi-blob-controller.yaml
  deploy/v1.23.3/csi-blob-controller.yaml
  deploy/v1.23.4/csi-blob-controller.yaml
  deploy/v1.24.0/csi-blob-controller.yaml
  deploy/v1.24.1/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test
