Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-04, with the labels that each got.

#1326 feat: use new restricted liveness probe endpoint
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.23.3/blob-csi-driver-v1.23.3.tgz
  charts/v1.23.3/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.3/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.24.0/blob-csi-driver-v1.24.0.tgz
  charts/v1.24.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.0/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.3/csi-blob-controller.yaml
  deploy/v1.23.3/csi-blob-node.yaml
  deploy/v1.24.0/csi-blob-controller.yaml
  deploy/v1.24.0/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1327 fix: enable http with track2 sdk
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils/options.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils/transport.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1325 feat: support setting kubelet path for blobfuse-proxy endpoint
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes, lgtm

#1334 feat: upgrade to azcopy v10.24.0 for volume clone feature
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1337 [release-1.24] feat: use new restricted liveness probe endpoint
  charts/latest/blob-csi-driver-v1.24.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1338 [release-1.23] feat: use new restricted liveness probe endpoint
  charts/latest/blob-csi-driver-v1.23.4.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1342 [release-1.24] feat: support setting kubelet path for blobfuse-proxy endpoint
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: size/S, approved, cncf-cla: yes, lgtm

#1353 test: ignore azcopy CVE-2023-45288
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1354 fix: CVE-2023-45288
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1352 chore: set node_get_volume_stats log level to 6
  go.mod
  go.sum
  pkg/blob/nodeserver.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/util.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/accesscontrol.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/configuration.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/iputil/prefix.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/securitygroup/securitygroup.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/L

#1355 fix: CVE-2023-45288
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1359 [release-1.24] chore: set node_get_volume_stats log level to 6
  go.mod
  go.sum
  pkg/blob/nodeserver.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azidentity.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/go.work.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/test-resources.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/time_unix.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/challenge_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/ci.keyvault.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/doc.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal/parse.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/confidential/confidential.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/public/public.go
  vendor/github.com/golang-jwt/jwt/v5/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v5/hmac.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/arm_conf.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/armauth/auxiliary_auth_policy.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/armauth/keyvault_credential.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth_conf.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/util.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/accesscontrol.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/configuration.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/iputil/prefix.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/securitygroup/securitygroup.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
Labels: size/XXL, approved, cncf-cla: yes, kind/cleanup

#1366 [release-1.23] fix: enable http with track2 sdk
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/gocovmerge.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/profiles_and_reports.go
  vendor/github.com/onsi/ginkgo/v2/internal/node.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/reporting_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/golang.org/x/tools/cover/profile.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/contextual_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/k8s.io/klog/v2/safeptr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_auth.go
Labels: kind/bug, approved, cncf-cla: yes, size/XL

#1367 fix: CVE-2024-3177
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/wsstream/conn.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/cel/composition.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/controller_reconcile.go
  vendor/k8s.io/apiserver/pkg/cel/environment/base.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache_interval.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/k8s.io/client-go/tools/remotecommand/websocket.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1368 [release-1.24] fix: CVE-2024-3177
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/wsstream/conn.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/cel/composition.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/controller_reconcile.go
  vendor/k8s.io/apiserver/pkg/cel/environment/base.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache_interval.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/k8s.io/client-go/tools/remotecommand/websocket.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1369 [release-1.23] fix: CVE-2024-3177
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/wsstream/conn.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/cel/composition.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/controller_reconcile.go
  vendor/k8s.io/apiserver/pkg/cel/environment/base.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache_interval.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/k8s.io/client-go/tools/remotecommand/websocket.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1370 [release-1.22] fix: CVE-2024-3177
  go.mod
  go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/k8s.io/apiserver/pkg/endpoints/discovery/aggregated/handler.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes
