Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-02, with the labels that each got.

#1232 [release-1.23] fix: increase volume cloning timeout
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  test/sanity/run-test.sh
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1234 test: fix sanity test failure
  test/sanity/run-test.sh
Labels: kind/test, approved, cncf-cla: yes, size/XS

#1235 feat: install blobfuse 2.2.0 as default version
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.22.5/blob-csi-driver-v1.22.5.tgz
  charts/v1.22.5/blob-csi-driver/values.yaml
  charts/v1.23.3/blob-csi-driver-v1.23.3.tgz
  charts/v1.23.3/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.22.5/csi-blob-node.yaml
  deploy/v1.23.3/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1238 doc: add this repo to ArtifactHub
  README.md
  charts/artifacthub-repo.yml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1242 feat: upgrade to aznfs 2.0.4 version for nfs mount
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1245 cleanup: remove integration test
  Makefile
  test/integration/README.md
  test/integration/integration_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/cleanup, size/L

#1246 test: fix goveralls
  .github/workflows/linux.yaml
Labels: size/S, approved, cncf-cla: yes, kind/failing-test

#1250 fix: panic when controller does not have cloud config
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1252 [release-1.22] fix: panic when controller does not have cloud config
  pkg/blob/azure.go
  pkg/blob/azure_test.go
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1255 doc: cut v1.24.0 release
  README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.24.0/blob-csi-driver-v1.24.0.tgz
  charts/v1.24.0/blob-csi-driver/Chart.yaml
  charts/v1.24.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.24.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.24.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.24.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.24.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.24.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.24.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.24.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.24.0/blob-csi-driver/values.yaml
  deploy/v1.24.0/csi-blob-controller.yaml
  deploy/v1.24.0/csi-blob-driver.yaml
  deploy/v1.24.0/csi-blob-node.yaml
  deploy/v1.24.0/kustomization.yaml
  deploy/v1.24.0/rbac-csi-blob-controller.yaml
  deploy/v1.24.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.24.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1256 chore: Update csi-blob-driver.yaml
  deploy/csi-blob-driver.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm

#1258 fix: add tokenRequests on v1.23.3, v1.24.0 in kubectl install
  deploy/v1.23.3/csi-blob-driver.yaml
  deploy/v1.24.0/csi-blob-driver.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1259 feat: allow multiple subnets in updating service endpoints
  docs/driver-parameters.md
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/feature, approved, cncf-cla: yes, size/M

#1262 chore: Update workload-identity-static-pv-mount.md
  docs/workload-identity-static-pv-mount.md
Labels: approved, cncf-cla: yes, size/XS, lgtm

#1263 feat: install blobfuse 2.2.1 as default version
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.3/blob-csi-driver-v1.23.3.tgz
  charts/v1.23.3/blob-csi-driver/values.yaml
  charts/v1.24.0/blob-csi-driver-v1.24.0.tgz
  charts/v1.24.0/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.23.3/csi-blob-node.yaml
  deploy/v1.24.0/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1264 fix: ensure azure cloud config could be loaded from secret
  pkg/blob/azure.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS
