Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#1674 test: fix trivy action
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1680 [release-1.24] fix: don't install blobfuse v1 by default since it's deprecated
  Makefile
  charts/latest/blob-csi-driver-v1.24.5.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1682 [release-1.22] fix: don't install blobfuse v1 by default since it's deprecated
  Makefile
  charts/latest/blob-csi-driver-v1.22.9.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1681 [release-1.23] fix: don't install blobfuse v1 by default since it's deprecated
  Makefile
  charts/latest/blob-csi-driver-v1.23.9.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/install-proxy.sh
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1683 [release-1.25] fix: don't install blobfuse v1 by default since it's deprecated
  Makefile
  charts/latest/blob-csi-driver-1.25.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
  pkg/blobfuse-proxy/init.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1678 feat: upgrade to azcopy v10.27.0 for volume clone
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1691 fix: tagValueDelimiter parameter mismatch
  pkg/blob/blob.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1695 feat: upgrade to azcopy v10.27.1 for volume clone
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1699 fix: change mount timeout to 1.5min
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#1704 cleanup: remove unused livenessProbe in registrar
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1707 [release-1.23] cleanup: remove unused livenessProbe in registrar
  charts/latest/blob-csi-driver-v1.23.9.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1706 [release-1.24] cleanup: remove unused livenessProbe in registrar
  charts/latest/blob-csi-driver-v1.24.5.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1705 [release-1.25] cleanup: remove unused livenessProbe in registrar
  charts/latest/blob-csi-driver-1.25.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1708 Group all deps update into one pr.
  .github/dependabot.yaml
Labels: kind/test, approved, cncf-cla: yes, size/XS, lgtm

#1710 chore: update CSI spec to v1.10.0
  go.mod
  go.sum
  pkg/blob/blob.go
  pkg/blob/identityserver_test.go
  pkg/blob/nodeserver.go
  pkg/blob/nodeserver_test.go
  pkg/csi-common/utils_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm

#1717 feat: add chart parameter for install-blobfuse-proxy ability to disable setReadAheadSize
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#1723 fix: always start blobfuse-proxy as long as it's enabled
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes, lgtm

#1722 [release-1.23] fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/blob-csi-driver-v1.23.9.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1721 [release-1.24] fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/blob-csi-driver-v1.24.5.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1720 [release-1.25] fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/blob-csi-driver-1.25.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1719 fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1725 fix: increase blob memory limit to avoid OOM during volume clone
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS, do-not-merge/hold

#1726 [release-1.25] fix: increase blob memory limit to avoid OOM during volume clone
  charts/README.md
  charts/latest/blob-csi-driver-1.25.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS, do-not-merge/hold

#1727 [release-1.24] fix: increase blob memory limit to avoid OOM during volume clone
  charts/README.md
  charts/latest/blob-csi-driver-v1.24.5.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1728 [release-1.23] fix: increase blob memory limit to avoid OOM during volume clone
  charts/README.md
  charts/latest/blob-csi-driver-v1.23.9.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS, do-not-merge/hold
