Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-03, with the labels that each got.

#1272 fix: nfs volume created in storage account that has blobfuse volume
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/core.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/etag.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported/response_error.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/log/log.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/log/log.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/request.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_auth.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1276 feat: provide nfsv3 protocol to enforce nfs mount
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M

#1279 test: ignore azcopy CVE-2024-24786
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1278 fix: fix azcopy exec timeout func
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/volume_lock.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1286 feat: upgrade azcopy version to 10.23.0 for volume clone feature
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1290 fix: nfs mount stuck issue
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1291 Add group update policy for k8s.io dependencies
  .github/dependabot.yaml
Labels: kind/test, approved, cncf-cla: yes, size/XS, lgtm

#1289 chore: only use sas token for azcopy when useDataPlaneAPI is used
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1298 cleanup: rename WaitUntilTimeout func
  pkg/blob/controllerserver.go
  pkg/blob/nodeserver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1303 chore: refine sastoken cache
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: approved, cncf-cla: yes, size/M, kind/cleanup

#1309 fix: strip service account token
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1318 fix: workload identity did not work
  pkg/blob/azure.go
  pkg/blob/azure_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
