Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#1622 fix: nfs mount failure on arm64 node
  pkg/blobplugin/Dockerfile
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1630 chore: enable blobfuse-proxy by default in kubectl install
  deploy/csi-blob-node.yaml
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/deployment-nfs.yaml
  deploy/example/deployment.yaml
  deploy/example/nfs/statefulset.yaml
  deploy/example/nginx-blobfuse-inline-volume.yaml
  deploy/example/nginx-pod-blob.yaml
  deploy/example/statefulset-nfs.yaml
  deploy/example/statefulset.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1633 feat: install blobfuse2 for arm64
  pkg/blobplugin/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, ok-to-test

#1634 fix: install blobfuse2 on arm64 node by blobfuse-proxy
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1640 doc: cut v1.25.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.25.0/blob-csi-driver-1.25.0.tgz
  charts/v1.25.0/blob-csi-driver/Chart.yaml
  charts/v1.25.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.25.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.25.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.25.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.25.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.25.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.25.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.25.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.25.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.25.0/blob-csi-driver/values.yaml
  deploy/v1.25.0/csi-blob-controller.yaml
  deploy/v1.25.0/csi-blob-driver.yaml
  deploy/v1.25.0/csi-blob-node.yaml
  deploy/v1.25.0/kustomization.yaml
  deploy/v1.25.0/rbac-csi-blob-controller.yaml
  deploy/v1.25.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.25.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1642 doc: remove obsolete doc about volumeID format
  deploy/example/e2e_usage.md
  deploy/example/pv-blobfuse-auth.yaml
  deploy/example/pv-blobfuse-csi-keyvault.yaml
  deploy/example/pv-blobfuse-csi.yaml
  deploy/example/pv-blobfuse-nfs.yaml
  docs/driver-parameters.md
  docs/workload-identity-static-pv-mount.md
Labels: size/S, approved, cncf-cla: yes, kind/documentation

#1643 doc: update new chart versions
  README.md
  charts/index.yaml
  charts/v1.22.9/blob-csi-driver-v1.22.9.tgz
  charts/v1.22.9/blob-csi-driver/Chart.yaml
  charts/v1.22.9/blob-csi-driver/templates/NOTES.txt
  charts/v1.22.9/blob-csi-driver/templates/_helpers.tpl
  charts/v1.22.9/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.22.9/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.22.9/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.22.9/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.22.9/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.22.9/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.22.9/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.22.9/blob-csi-driver/values.yaml
  charts/v1.23.9/blob-csi-driver-v1.23.9.tgz
  charts/v1.23.9/blob-csi-driver/Chart.yaml
  charts/v1.23.9/blob-csi-driver/templates/NOTES.txt
  charts/v1.23.9/blob-csi-driver/templates/_helpers.tpl
  charts/v1.23.9/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.9/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.23.9/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.23.9/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.23.9/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.23.9/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.23.9/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.23.9/blob-csi-driver/values.yaml
  charts/v1.24.5/blob-csi-driver-v1.24.5.tgz
  charts/v1.24.5/blob-csi-driver/Chart.yaml
  charts/v1.24.5/blob-csi-driver/templates/NOTES.txt
  charts/v1.24.5/blob-csi-driver/templates/_helpers.tpl
  charts/v1.24.5/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.5/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.24.5/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.24.5/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.24.5/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.24.5/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.24.5/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.24.5/blob-csi-driver/values.yaml
  deploy/v1.22.9/csi-blob-controller.yaml
  deploy/v1.22.9/csi-blob-driver.yaml
  deploy/v1.22.9/csi-blob-node.yaml
  deploy/v1.22.9/kustomization.yaml
  deploy/v1.22.9/rbac-csi-blob-controller.yaml
  deploy/v1.22.9/rbac-csi-blob-node.yaml
  deploy/v1.23.9/csi-blob-controller.yaml
  deploy/v1.23.9/csi-blob-driver.yaml
  deploy/v1.23.9/csi-blob-node.yaml
  deploy/v1.23.9/kustomization.yaml
  deploy/v1.23.9/rbac-csi-blob-controller.yaml
  deploy/v1.23.9/rbac-csi-blob-node.yaml
  deploy/v1.24.5/csi-blob-controller.yaml
  deploy/v1.24.5/csi-blob-driver.yaml
  deploy/v1.24.5/csi-blob-node.yaml
  deploy/v1.24.5/kustomization.yaml
  deploy/v1.24.5/rbac-csi-blob-controller.yaml
  deploy/v1.24.5/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.22.9.md
  docs/install-csi-driver-v1.23.9.md
  docs/install-csi-driver-v1.24.5.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1647 fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.9/blob-csi-driver-v1.23.9.tgz
  charts/v1.23.9/blob-csi-driver/values.yaml
  charts/v1.24.5/blob-csi-driver-v1.24.5.tgz
  charts/v1.24.5/blob-csi-driver/values.yaml
  charts/v1.25.0/blob-csi-driver-1.25.0.tgz
  charts/v1.25.0/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/v1.23.9/csi-blob-controller.yaml
  deploy/v1.23.9/csi-blob-node.yaml
  deploy/v1.24.5/csi-blob-controller.yaml
  deploy/v1.24.5/csi-blob-node.yaml
  deploy/v1.25.0/csi-blob-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1650 [release-1.23] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/blob-csi-driver-v1.23.9.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.23.9/blob-csi-driver-v1.23.9.tgz
  charts/v1.23.9/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/v1.23.9/csi-blob-controller.yaml
  deploy/v1.23.9/csi-blob-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1649 [release-1.24] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/blob-csi-driver-v1.24.5.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.24.5/blob-csi-driver-v1.24.5.tgz
  charts/v1.24.5/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/v1.24.5/csi-blob-controller.yaml
  deploy/v1.24.5/csi-blob-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1648 [release-1.25] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/blob-csi-driver-1.25.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.25.0/blob-csi-driver-1.25.0.tgz
  charts/v1.25.0/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/v1.25.0/csi-blob-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1651 fix: skip blobfuse-proxy copy if it's not enabled in driver init
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1660 fix: blobfuse install failure in install-blobfuse-proxy initContainer
  pkg/blobplugin/Dockerfile
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1665 test: add UserAgent for e2e client
  test/utils/azure/azure_helper.go
Labels: kind/test, approved, cncf-cla: yes, size/XS, lgtm
