Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#1455 [release-1.23] fix: add azcopy-dir since volume cloning supported from v1.23.2
  charts/latest/blob-csi-driver-v1.23.6.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.2/blob-csi-driver-v1.23.2.tgz
  charts/v1.23.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.3/blob-csi-driver-v1.23.3.tgz
  charts/v1.23.3/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
  charts/v1.23.4/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.5/blob-csi-driver-v1.23.5.tgz
  charts/v1.23.5/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.23.6/blob-csi-driver-v1.23.6.tgz
  charts/v1.23.6/blob-csi-driver/templates/csi-blob-controller.yaml
  deploy/csi-blob-controller.yaml
  deploy/v1.23.2/csi-blob-controller.yaml
  deploy/v1.23.3/csi-blob-controller.yaml
  deploy/v1.23.4/csi-blob-controller.yaml
  deploy/v1.23.5/csi-blob-controller.yaml
  deploy/v1.23.6/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1456 doc: deprecate AzureStorageIdentityObjectID field
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1457 test: fix trivy action failure
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS

#1461 feat: add tag value delimiter
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1464 doc: add blobfuse mount with managed identity doc
  deploy/example/blobfuse-mi/README.md
  deploy/example/blobfuse-mi/pv-blobfuse-mi.yaml
  deploy/example/blobfuse-mi/storageclass-blobfuse-mi.yaml
Labels: cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#1473 cleanup: refine logs
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#1476 cleanup: refine logs
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#1475 [release-1.23] cleanup: refine logs
  pkg/blob/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#1470 feat: add allowSharedKeyAccess parameter
  docs/driver-parameters.md
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/S, approved, cncf-cla: yes, lgtm, ok-to-test

#1484 doc: add yamllint check
  deploy/example/blobfuse-mi/pv-blobfuse-mi.yaml
  deploy/example/blobfuse-mi/storageclass-blobfuse-mi.yaml
  hack/verify-yamllint.sh
Labels: size/S, approved, cncf-cla: yes, kind/documentation

#1482 [release-1.23] feat: add allowSharedKeyAccess parameter
  docs/driver-parameters.md
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/S, approved, cncf-cla: yes, lgtm, ok-to-test

#1483 test: add allowSharedKeyAccess feature unit test
  pkg/blob/controllerserver_test.go
Labels: kind/test, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#1485 test: upgrade csi-test to v5.2.0 for more test coverage
  test/sanity/run-tests-all-clouds.sh
Labels: kind/test, approved, cncf-cla: yes, size/XS

#1490 feat: add metadata tag on the storage account created by the driver
  pkg/blob/controllerserver.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#1496 fix: blobfuse mount failure in Azure Linux v3
  pkg/blobfuse-proxy/server/server.go
Labels: approved, cncf-cla: yes, size/XS, lgtm

#1502 [release-1.22] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/admission/plugin/cel/composition.go
  vendor/k8s.io/apiserver/pkg/endpoints/discovery/aggregated/handler.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go
  vendor/k8s.io/apiserver/pkg/server/options/recommended.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/interface.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/metrics.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XL

#1497 fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XL

#1500 [release-1.24] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XL

#1501 [release-1.23] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XL

#1505 doc: update new chart versions
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.24.2/blob-csi-driver-v1.24.2.tgz
  charts/v1.24.2/blob-csi-driver/Chart.yaml
  charts/v1.24.2/blob-csi-driver/templates/NOTES.txt
  charts/v1.24.2/blob-csi-driver/templates/_helpers.tpl
  charts/v1.24.2/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.2/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.24.2/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.24.2/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.24.2/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.24.2/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.24.2/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.24.2/blob-csi-driver/values.yaml
  deploy/v1.24.2/csi-blob-controller.yaml
  deploy/v1.24.2/csi-blob-driver.yaml
  deploy/v1.24.2/csi-blob-node.yaml
  deploy/v1.24.2/kustomization.yaml
  deploy/v1.24.2/rbac-csi-blob-controller.yaml
  deploy/v1.24.2/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.24.2.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1504 fix: clone volume content to requested volume
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1508 fix: ignore specific blobfuse version install failure
  pkg/blobfuse-proxy/install-proxy.sh
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1510 cleanup: refine copy volume logic
  pkg/blob/controllerserver.go
Labels: approved, cncf-cla: yes, size/M, kind/cleanup

#1515 fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.24.2/blob-csi-driver-v1.24.2.tgz
  charts/v1.24.2/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  deploy/rbac-csi-blob-controller.yaml
  deploy/v1.24.2/rbac-csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1517 fix: volume cloning between different storage account for BlobAccessTierNotSupportedForAccountType error
  pkg/blob/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test
