Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#1854 chore: upgrade lib
  go.mod
  go.sum
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/accesstokens/accesstokens.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/ast/inspector/iter.go
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/golang.org/x/tools/go/ast/inspector/walk.go
  vendor/golang.org/x/tools/internal/astutil/edge/edge.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, kind/cleanup

#1855 feat: upgrade aznfs package to v2.0.11
  pkg/blobplugin/Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1858 fix: incomplete azcopy job state during volume clone
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1861 fix: incorrect cloud provider setting in sovereign cloud
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_publicip_repo.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M

#1862 fix: downgrade api-version for sovereign cloud
  go.mod
  go.sum
  vendor/golang.org/x/net/context/context.go
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/internal/httpcommon/headermap.go
  vendor/golang.org/x/net/internal/httpcommon/request.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/.golangci.yml
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/Makefile
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/accountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/accountclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobcontainerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobcontainerclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobservicepropertiesclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobservicepropertiesclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cloud.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/factory_gen.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileservicepropertiesclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileservicepropertiesclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/ipgroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/ipgroupclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/registryclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/registryclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils/cloud.go
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1866 fix: account match algorithm when source account name is provided
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/storage/azure_storageaccount.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1853 doc: cut v1.26.0 release
  README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/v1.26.0/blob-csi-driver-1.26.0.tgz
  charts/v1.26.0/blob-csi-driver/Chart.yaml
  charts/v1.26.0/blob-csi-driver/templates/NOTES.txt
  charts/v1.26.0/blob-csi-driver/templates/_helpers.tpl
  charts/v1.26.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.26.0/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.26.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.26.0/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.26.0/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.26.0/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.26.0/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.26.0/blob-csi-driver/values.yaml
  deploy/v1.26.0/csi-blob-controller.yaml
  deploy/v1.26.0/csi-blob-driver.yaml
  deploy/v1.26.0/csi-blob-node.yaml
  deploy/v1.26.0/kustomization.yaml
  deploy/v1.26.0/rbac-csi-blob-controller.yaml
  deploy/v1.26.0/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.26.0.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1871 [release-1.24] fix: CVE-2024-51744
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1872 fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/README.md
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  charts/v1.26.0/blob-csi-driver-1.26.0.tgz
  charts/v1.26.0/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.26.0/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.26.0/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1873 [release-1.26] fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/README.md
  charts/index.yaml
  charts/latest/blob-csi-driver-1.26.0.tgz
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1875 [release-1.24] fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/README.md
  charts/latest/blob-csi-driver-v1.24.7.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1874 [release-1.25] fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/README.md
  charts/latest/blob-csi-driver-1.25.3.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1876 doc: update new chart versions
  README.md
  charts/index.yaml
  charts/v1.24.7/blob-csi-driver-v1.24.7.tgz
  charts/v1.24.7/blob-csi-driver/Chart.yaml
  charts/v1.24.7/blob-csi-driver/templates/NOTES.txt
  charts/v1.24.7/blob-csi-driver/templates/_helpers.tpl
  charts/v1.24.7/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.24.7/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.24.7/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.24.7/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.24.7/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.24.7/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.24.7/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.24.7/blob-csi-driver/values.yaml
  charts/v1.25.3/blob-csi-driver-1.25.3.tgz
  charts/v1.25.3/blob-csi-driver/Chart.yaml
  charts/v1.25.3/blob-csi-driver/templates/NOTES.txt
  charts/v1.25.3/blob-csi-driver/templates/_helpers.tpl
  charts/v1.25.3/blob-csi-driver/templates/csi-blob-controller.yaml
  charts/v1.25.3/blob-csi-driver/templates/csi-blob-driver.yaml
  charts/v1.25.3/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.25.3/blob-csi-driver/templates/rbac-csi-blob-controller.yaml
  charts/v1.25.3/blob-csi-driver/templates/rbac-csi-blob-node.yaml
  charts/v1.25.3/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml
  charts/v1.25.3/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml
  charts/v1.25.3/blob-csi-driver/values.yaml
  deploy/v1.24.7/csi-blob-controller.yaml
  deploy/v1.24.7/csi-blob-driver.yaml
  deploy/v1.24.7/csi-blob-node.yaml
  deploy/v1.24.7/kustomization.yaml
  deploy/v1.24.7/rbac-csi-blob-controller.yaml
  deploy/v1.24.7/rbac-csi-blob-node.yaml
  deploy/v1.25.3/csi-blob-controller.yaml
  deploy/v1.25.3/csi-blob-driver.yaml
  deploy/v1.25.3/csi-blob-node.yaml
  deploy/v1.25.3/kustomization.yaml
  deploy/v1.25.3/rbac-csi-blob-controller.yaml
  deploy/v1.25.3/rbac-csi-blob-node.yaml
  docs/install-blob-csi-driver.md
  docs/install-csi-driver-v1.24.7.md
  docs/install-csi-driver-v1.25.3.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation

#1878 chore: increase liveness-probe timeout
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.24.7/blob-csi-driver-v1.24.7.tgz
  charts/v1.24.7/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.25.3/blob-csi-driver-1.25.3.tgz
  charts/v1.25.3/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.26.0/blob-csi-driver-1.26.0.tgz
  charts/v1.26.0/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.24.7/csi-blob-node.yaml
  deploy/v1.25.3/csi-blob-node.yaml
  deploy/v1.26.0/csi-blob-node.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/M

#1880 [release-1.25] chore: increase liveness-probe timeout
  charts/latest/blob-csi-driver-1.25.3.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/v1.25.3/blob-csi-driver-1.25.3.tgz
  charts/v1.25.3/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
  deploy/v1.25.3/csi-blob-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1882 test: ignore CVE-2025-22870 in azcopy
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1798 feat: support workload identity
  docs/workload-identity-static-pv-mount.md
  pkg/blob/blob.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M

#1895 [release-1.26] chore: upgrade azure cloud provider lib
  .github/workflows/static.yaml
  go.mod
  go.sum
  pkg/csi-common/driver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  vendor/github.com/Azure/msi-dataplane/pkg/dataplane/reloadCredentials.go
  vendor/github.com/prometheus/client_golang/prometheus/atomic_update.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.c
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_not_supported.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/go.opentelemetry.io/otel/exporters/prometheus/exporter.go
  vendor/go.opentelemetry.io/otel/sdk/metric/internal/aggregate/exponential_histogram.go
  vendor/go.opentelemetry.io/otel/sdk/metric/version.go
  vendor/go.opentelemetry.io/otel/sdk/resource/os_release_darwin.go
  vendor/go.opentelemetry.io/otel/sdk/resource/resource.go
  vendor/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go
  vendor/go.opentelemetry.io/otel/sdk/trace/sampling.go
  vendor/go.opentelemetry.io/otel/sdk/trace/simple_span_processor.go
  vendor/go.opentelemetry.io/otel/sdk/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/accountclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobcontainerclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobservicepropertiesclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileservicepropertiesclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/trace/provider.go
Labels: kind/feature, approved, cncf-cla: yes, size/XL

#1894 chore: upgrade azure cloud provider lib
  .github/workflows/static.yaml
  go.mod
  go.sum
  pkg/csi-common/driver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  vendor/github.com/Azure/msi-dataplane/pkg/dataplane/reloadCredentials.go
  vendor/github.com/prometheus/client_golang/prometheus/atomic_update.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.c
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_not_supported.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/go.opentelemetry.io/otel/exporters/prometheus/exporter.go
  vendor/go.opentelemetry.io/otel/sdk/metric/internal/aggregate/exponential_histogram.go
  vendor/go.opentelemetry.io/otel/sdk/metric/version.go
  vendor/go.opentelemetry.io/otel/sdk/resource/os_release_darwin.go
  vendor/go.opentelemetry.io/otel/sdk/resource/resource.go
  vendor/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go
  vendor/go.opentelemetry.io/otel/sdk/trace/sampling.go
  vendor/go.opentelemetry.io/otel/sdk/trace/simple_span_processor.go
  vendor/go.opentelemetry.io/otel/sdk/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/accountclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobcontainerclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobservicepropertiesclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileservicepropertiesclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/trace/provider.go
Labels: kind/feature, approved, cncf-cla: yes, size/XL

#1896 feat: add metrics on node config
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1897 [release-1.26] feat: add metrics on node config
  charts/latest/blob-csi-driver-1.26.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1898 [release-1.25] feat: add metrics on node config
  charts/latest/blob-csi-driver-1.25.3.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1905 fix: CVE-2025-30204
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1907 [release-1.25] fix: CVE-2025-30204
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1914 chore: upgrade azcopy to v10.28.1
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS
