Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2025-09, with the labels that each got.

#2163 fix: China cloud endpoints
  go.mod
  go.sum
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/local/server.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/authority/authority.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/resolvers.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/M

#2173 fix(proxy_installer): add necessary mounts for cos,gardenlinux bin paths
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2174 [release-1.26] fix(proxy_installer): add necessary mounts for cos, gardenlinux bin paths
  charts/latest/blob-csi-driver-1.26.7.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
Labels: kind/bug, approved, cncf-cla: yes, size/M

#2175 test: refine verify-helm-chart-index.sh
  hack/verify-helm-chart-index.sh
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#2176 [release-1.27] fix(proxy_installer): add necessary mounts for cos,gardenlinux bin paths
  charts/latest/blob-csi-driver-1.27.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  pkg/blobfuse-proxy/install-proxy-rhcos.sh
Labels: kind/bug, approved, cncf-cla: yes, size/M
