Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2025-08, with the labels that each got.

#2102 feat: support blobStorageAccountType parameter in storage class or pv
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  pkg/blob/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2107 cleanup: unused blobfuseVersion
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-node.yaml
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#2111 test: fix CVE-2025-47907 traivy test failure
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#2110 chore: upgrade azcopy to v10.30.0
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#2124 doc: fix outdated doc
  deploy/blobfuse-proxy/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#2130 cleanup: add more logging in blobfuse-proxy when blobfuse2 not found
  pkg/blobfuse-proxy/server/server.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#2135 chore: upgrade CSI driver sidecar images
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2137 feat: support blobfuse2 preview package install
  pkg/blobfuse-proxy/install-proxy.sh
Labels: size/S, approved, cncf-cla: yes, lgtm, ok-to-test, tide/merge-method-squash

#2144 test: ignore latest tgz file in helm chart index verification
  hack/verify-helm-chart-index.sh
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#2148 Improve test-coverage on blobplugin
  pkg/blobplugin/main_test.go
Labels: kind/test, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2153 [release-1.25] fix: CVE-2025-5187
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/routes.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L
