Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2025-06, with the labels that each got.

#2019 Revert "cleanup: disable version check in blobfuse2 driver by default"
  pkg/blob/blob.go
  pkg/blob/blob_test.go
Labels: size/S, approved, cncf-cla: yes

#2020 Revert "[release-1.25] cleanup: disable version check in blobfuse2 driver by default"
  pkg/blob/blob.go
  pkg/blob/blob_test.go
Labels: size/S, approved, cncf-cla: yes

#2024 cleanup: disable version check in blobfuse2 driver by default
  pkg/blobfuse-proxy/server/server.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#2028 chore: migrate csi-resizer sidecar image to dalec image
  charts/latest/blob-csi-driver-v0.0.0.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#2030 [release-1.25] chore: migrate csi-resizer sidecar image to dalec image
  charts/latest/blob-csi-driver-1.25.8.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
  deploy/csi-blob-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#2039 [release-1.23] test: fix golint errors
  .github/workflows/static.yaml
  pkg/csi-common/driver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, size/M, kind/failing-test

#2043 [release-1.26] chore: migrate csi driver sidecar images to dalec images
  charts/latest/blob-csi-driver-1.26.5.tgz
  charts/latest/blob-csi-driver/values.yaml
  deploy/csi-blob-controller.yaml
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#2041 fix: only use the permission bits for chmod
  pkg/blob/blob.go
  pkg/blob/blob_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M

#2053 fix: CVE-2025-4563
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/common.go
  vendor/k8s.io/kubernetes/pkg/util/kernel/constants.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/M

#2054 [release-1.26] fix: CVE-2025-4563
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/common.go
  vendor/k8s.io/kubernetes/pkg/util/kernel/constants.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/M
