Repository kubernetes-sigs/blob-csi-driver, pull requests merged in 2025-04, with the labels that each got.

#1927 fix: storageEndPointSuffix setting in on-prem cluster
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1933 test: fix CVE-2025-22871 in trivy action
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1938 doc: add ClientID parameter in doc
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#1939 fix: allow clientID, tenantID workload identity parameters in storage class
  pkg/blob/blob.go
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1944 cleanup: remove deprecated wait.PollImediate function
  pkg/blob/controllerserver.go
  pkg/blob/controllerserver_test.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#1948 [release-1.26] fix: goroutine leak when timeout
  go.mod
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.golangci.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/scan.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1950 [release-1.24] fix: goroutine leak when timeout
  go.mod
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.golangci.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/scan.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1949 [release-1.25] fix: goroutine leak when timeout
  go.mod
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.golangci.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/scan.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1951 fix: grpc connection was not closed properly
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M

#1952 [release-1.26] fix: CVE-2025-22872
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1954 [release-1.24] fix: CVE-2025-22872
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1958 [release-1.23] fix: CVE-2025-22872
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1953 [release-1.25] fix: CVE-2025-22872
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, approved, cncf-cla: yes

#1960 test: ignore CVE-2025-22872 in azcopy
  .trivyignore
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#1964 fix: incorrect metris log in NodeStageVolume
  pkg/blob/nodeserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1971 feat: add VerticalPodAutoscaler to blob csi controller pod
  deploy/example/vpa/README.md
  deploy/example/vpa/install-components/admission-controller-deployment.yaml
  deploy/example/vpa/install-components/delete-webhook.sh
  deploy/example/vpa/install-components/gencerts.sh
  deploy/example/vpa/install-components/recommender-deployment.yaml
  deploy/example/vpa/install-components/rmcerts.sh
  deploy/example/vpa/install-components/updater-deployment.yaml
  deploy/example/vpa/install-components/vpa-rbac.yaml
  deploy/example/vpa/install-components/vpa-v1-crd-gen.yaml
  deploy/example/vpa/install-components/warn-obsolete-vpa-objects.sh
  deploy/example/vpa/install-vpa.sh
  deploy/example/vpa/uninstall-vpa.sh
  deploy/example/vpa/vertical-pod-autoscaler.yaml
  hack/verify-yamllint.sh
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test

#1970 doc: Remove the obsolete comment
  docs/workload-identity-deploy-csi-driver.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS, lgtm, ok-to-test

#1972 chore: upgrade k8s.io/mount-utils
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/doc.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1973 cleanup: refine Dockerfile
  pkg/blobplugin/Dockerfile
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup

#1974 chore: upgrade azcopy to v10.29.0
  .trivyignore
  pkg/blobplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS
